### PR TITLE
Add ability to copy the text produced by the feature details sequence panel to MS Word/Google Docs and preserve styling

### PR DESCRIPTION
**Pull request by cmdcolin**
This adds a button that says "Copy" (as in copy to clipboard) button for the feature details sequence panel, and the sequence can then be pasted in word or google docs and retain the coloring, and be used for microsoft word based bioinformatics

The code had to be modified slightly to support this (span instead of div)

### CODE REVIEW

**Comment by garrettjstevens** [comment]
Could this be a styled button or icon button instead of an unstyled button?

**Comment by cmdcolin** [comment]
Changed to an MUI button :)

**Comment by cmdcolin** [comment]
maybe I'll go ahead and merge this one, should be good to go

**Comment by rbuels** [comment]
does it also work with ctrl-c?

**Comment by cmdcolin** [comment]
Manual mouse-click-and-drag highlighting text and pressing ctrl+c works also still works. It did not work before though

Can see difference by trying out using

https://s3.amazonaws.com/jbrowse.org/code/jb2/v1.1.0/index.html?session=share-vkhofjwRbf&password=CTZiy

https://s3.amazonaws.com/jbrowse.org/code/jb2/main/index.html?session=share-vkhofjwRbf&password=CTZiy

**Pull request merged**
