### PR TITLE
Subtler minicontrols focus

### PR DESCRIPTION
**Pull request by cmdcolin**
This uses a less strong purple color for the minicontrols focus

### CODE REVIEW

**Comment by cmdcolin** [comment]
whitespace-ignored diff https://github.com/GMOD/jbrowse-components/pull/4034/files?w=1

**Comment by cmdcolin** [comment]
this PR
image

main branch
image

**Comment by cmdcolin** [comment]
any thoughts on this one. I think the subtler color is still less "alarming" visually

**Review by carolinebridge-oicr — APPROVED** [review]
I think this is acceptable! The difference is noticeable still imo; tested it with some colorblind filters too

**Pull request merged**
