### PR TITLE
Add note to user guide about variant callers that can be used for SV inspector

### PR DESCRIPTION
**Pull request by cmdcolin**

### CODE REVIEW

**Review by scottcain — APPROVED** [review]
Perfect! Thanks for doing this.

**Comment by cmdcolin** [comment]
sure thing, these types of doc updates are very useful for contextualizing how to get your data into jbrowse

**Comment by cmdcolin** [comment]
as long as we're here, we should also add support for more types of variants to be displayed in the circular view/breakpoint split view. currently, as noted in this PR, it is just TRA and breakends, but rendering (perhaps, focusing on large) deletions,insertions, and inversions would be useful also. mildly related issue https://github.com/GMOD/jbrowse-components/issues/672

**Comment by cmdcolin** [comment]
merge this for now though :)

**Pull request merged**
