### PR TITLE
Add react-error-boundary with App level fatal error message

### PR DESCRIPTION
**Pull request by cmdcolin**
This adds a basic ErrorSnackbar error boundary at the App level and a "FatalError" component if something happens above the App level

Note: Handling errors is tough, for example a mobx-state-tree ambiguous ID is very hard to catch properly as it errors out many components who try to read it's conf

Also note: this can give a stacktrace in dev, but in prod everything is minimized. This maybe is an interesting question of whether we should just ship a dev build to end users so they can more easily report us back stack traces

Addresses #321

### CODE REVIEW

**Comment by cmdcolin** [comment]
The reason I say the "Note: Handling errors is tough" is I started thinking about adding more granular error boundaries in this PR but it was difficult, so it is now just the App level and JBrowse level components having error boundary

**Comment by cmdcolin** [comment]
Pairing with Garrett today, we decided that ErrorBoundary is not useful for the snackbar, since ErrorBoundaries are a complete replacement component and they do not keep the original component. Therefore any snackbar would need to be used differently.

Therefore I just made a app level FatalError dialog

**Comment by cmdcolin** [comment]
Also, I had a big fight with jest-mock-console, which was a module I introduced, but which really messed with trying to test error boundariers, so it was removed

**Comment by cmdcolin** [comment]
FInally, I would propose potentially shipping a dev build of our app to end users, or if not, the stack traces from the error will not be meaningful. It may be helpful, at least for some time, to get useful stack traces

**Comment by rbuels** [comment]
Downside of shipping a dev build is that it's slower, but I guess that is probably ok for users of the beta

**Comment by cmdcolin** [comment]
I think that we have pretty good performance in our dev builds now. @garrettjstevens mentioned that there could be a hurdle in the process of convincing the build system to allow a dev build in a release electron package, but it seems like it's doable :)

**Comment by rbuels** [comment]
There is a lot of stuff in this PR besides error boundary things, I'm having trouble seeing what the error handling actually looks like

**Comment by cmdcolin** [comment]
The error handler is just the ErrorBoundary around the JBrowse.js components in jbrowse-desktop and jbrowse-web. The ErrorBoundary comes from 'react-error-boundary' and this uses FatalErrorDialog as a fallback component. This means that when this error occurs, it's unrecoverable and produces this dialog.

I apologize for the proliferation of unrelated changes in this PR and recent PRs. I like to keep them single topic. I sort of accidentally merged #677 into this branch and continued on with it

I'll can clean this up and re-propose

**Comment by garrettjstevens** [comment]
@cmdcolin the more I think about it, the more I think packaging a dev build in electron will be tricky. We need to create a single build directory for electron-builder to work with, and CRA just isn't set up to package a development build directory.

**Comment by rbuels** [comment]
I'm guilty of having lumped unrelated stuff into PRs before, it happens

**Pull request closed without merging**
