### PR TITLE
Add clickable navigation links to supplementary alignments/paired ends locations and BND/TRA endpoints in detail widgets

### PR DESCRIPTION
**Pull request by cmdcolin**
This creates "clickable locstrings" for supplementary alignments in the AlignmentFeatureDetails, and for breakends/translocations on VariantFeatureDetails

Example
localhost_3000__config=test_data%2Fconfig_demo json session=local-bHWWb4AhO

### CODE REVIEW

**Comment by cmdcolin** [comment]
Now uses a reference to the view that created the feature details panel in the navigation

Also added a panel for the VariantFeatureDetails for `<BND>/<TRA>` to automatically launch a breakpoint split view #1494

**Comment by cmdcolin** [comment]
Variant detail panel showing link to lgv and breakpoint split view


localhost_3000__config=test_data%2Fconfig_demo json session=local-mlN3tEAII

**Comment by cmdcolin** [comment]
This is probably ready for review, should work ok. Opinions on view being referenced from feature details panels ?

Randomly had to silence some warnings in tests because it warns when there are no views available for custom PluginManager([...plugins with no views])

**Comment by rbuels** [comment]
good to go if you just add that little check

**Pull request merged**
