### PR TITLE
Add `jbrowse sort-gff` subcommand

### PR DESCRIPTION
**Pull request by cmdcolin**
This helps automate the sorting of a gff, which can require tedious typing

This could be used in the Current Protocols paper also as a way to reduce steps

Assumes a unix-y type system with sh, sort, grep

### CODE REVIEW

**Comment by cmdcolin** [comment]
Usage

```
jbrowse sort-gff file.gff | bgzip > out.sorted.gff.gz
tabix out.sorted.gff.gz
```

**Comment by cmdcolin** [comment]
any thoughts on adding this to CLI @garrettjstevens ?

**Review by garrettjstevens — APPROVED** [review]
Yeah, looks good to me. `sort` does exist on Windows, but since `grep` does not, it should properly error out there. Also I think these commands should work on BSD `sort`/`grep` as well as GNU.

It could be worth a note in the description that this will not preserve the locations of comments or `###` sync directives, although that's the same probably no matter how you sort it.

**Comment by cmdcolin** [comment]
excellent, updated description. It actually now checks for 'sh' too because it uses needs to use 'sh' to launch the subshell syntax that is being used

**Pull request merged**
