### PR TITLE
Fix weird behavior found when zooming close to the max/min values of the slider

### PR DESCRIPTION
**Pull request by cmdcolin**
Addresses #1053 

I added some sort of random heuristics but it disables the zoom in button when the slider is fully to the right or left, and also disables the zoomTo function behavior if there is basically a value that it interprets to be too close (and console.warn's rounding error)

### CODE REVIEW

**Comment by garrettjstevens** [comment]
I think this fixes the behavior where the zoom in button isn't disabled when it should be, but I'm still getting the weird "launching to another place" behavior described in #1053. I think I have a fix, though. Mind if I push a commit to this branch?

**Comment by cmdcolin** [comment]
go for it

**Comment by cmdcolin** [comment]
This looks good to me. While we are looking at the slider issue, do you have any feedback on https://github.com/GMOD/jbrowse-components/issues/1053#issuecomment-656688256 

The slider is quite narrow, and I think it feels kind of crazy when sliding, it might be better if debounced

**Comment by garrettjstevens** [comment]
Yeah, now that zoom levels aren't fixed, dragging the slider is a bit clumsy. It might feel a bit smoother if we did something like:

```diff
diff --git a/packages/linear-genome-view/src/LinearGenomeView/components/ZoomControls.tsx b/packages/linear-genome-view/src/LinearGenomeView/components/ZoomControls.tsx
--- a/packages/linear-genome-view/src/LinearGenomeView/components/ZoomControls.tsx
+++ b/packages/linear-genome-view/src/LinearGenomeView/components/ZoomControls.tsx
@@ -39,10 +39,10 @@ function ZoomControls({ model }: { model: LGV }) {
 
       <Slider
         className={classes.slider}
-        value={-Math.log2(model.bpPerPx)}
-        min={-Math.log2(model.maxBpPerPx)}
-        max={-Math.log2(model.minBpPerPx)}
-        onChange={(event, value) => model.zoomTo(2 ** -value)}
+        value={-Math.log2(model.bpPerPx) * 100}
+        min={-Math.log2(model.maxBpPerPx) * 100}
+        max={-Math.log2(model.minBpPerPx) * 100}
+        onChange={(event, value) => model.zoomTo(2 ** (-value / 100))}
       />
       <IconButton
         data-testid="zoom_in"
```

Also, I'm interpreting debouncing as "only fire after mouseup", and I think that could help. Really, though, it just needs to be wider to be useful, but there's not a great place I can think of to put it. Maybe since we have the overview bar and other ways to zoom now, the slider isn't needed? I used to look at the slider to give a sense of how far zoomed in I was, but now I use the overview for that. I don't know what other people use the slider for, though.

**Comment by rbuels** [comment]
you guys want to add debouncing here, or merge as is?

**Comment by cmdcolin** [comment]
This is a simple bugfix to the way things are but I think further we would need to decide to debounce or remove slider completely.

**Comment by cmdcolin** [comment]
I added debouncing plus the *100 suggestion and it feels a lot smoother with the *100 and less jerky with the debouncing. Would be cool to have smooth animate across scales but not sure we're quite there, but this seems like it is better this way for now

**Pull request merged**
