### PR TITLE
WIP - Fix protein widget  - Do No Merge

### PR DESCRIPTION
**Pull request by nathandunn**
- [ ] fix installation of assemblyManager being null (below)
- [ ] add automated tests
- [ ] wire into remote adapter (e.g., public Apollo track)

### CODE REVIEW

**Comment by nathandunn** [comment]
@rbuels  Is there a proper way to do wire in the assemblyManager? 

```
mobx.module.js:1776 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[JmEmipgbMX/protein:KRAS:1-40 rendering]' TypeError: Cannot read property 'assemblyData' of undefined
    at renderBlockData (serverSideRenderedBlock.js:40)
    at eval (serverSideRenderedBlock.js:221)
    at eval (mobx.module.js:2098)
    at trackDerivedFunction (mobx.module.js:1212)
    at Reaction.track (mobx.module.js:1747)
    at reactionRunner (mobx.module.js:2097)
    at Reaction.eval [as onInvalidate] (mobx.module.js:2085)
    at Reaction.runReaction (mobx.module.js:1713)
    at runReactionsHelper (mobx.module.js:1850)
    at reactionScheduler (mobx.module.js:1828)
```

The error is the last line:

```
function renderBlockData(self) {
  var track = Object(mobx_state_tree__WEBPACK_IMPORTED_MODULE_4__["getParent"])(self, 2);
  var view = Object(_gmod_jbrowse_core_util_tracks__WEBPACK_IMPORTED_MODULE_9__["getContainingView"])(track);

  var _getRoot = Object(mobx_state_tree__WEBPACK_IMPORTED_MODULE_4__["getRoot"])(view),
      rpcManager = _getRoot.rpcManager,
      assemblyManager = _getRoot.assemblyManager;

  var trackConf = track.configuration;
  var trackConfParent = Object(mobx_state_tree__WEBPACK_IMPORTED_MODULE_4__["getParent"])(trackConf);
  if (!trackConfParent.assemblyName) trackConfParent = Object(mobx_state_tree__WEBPACK_IMPORTED_MODULE_4__["getParent"])(trackConfParent);
  var trackAssemblyName = Object(_gmod_jbrowse_core_configuration__WEBPACK_IMPORTED_MODULE_6__["readConfObject"])(trackConfParent, 'assemblyName');
  var trackAssemblyData = assemblyManager.assemblyData.get(trackAssemblyName) || {};
```

**Comment by nathandunn** [comment]
Called from the last line here off of the [Viewer.js[(https://github.com/GMOD/jbrowse-components/blob/create-gene-widget-v1/packages/protein-widget/src/Viewer.js#L103):

```
this.rpcManager = new _gmod_jbrowse_core_rpc_RpcManager__WEBPACK_IMPORTED_MODULE_11__["default"](this.pluginManager, this.model.configuration.rpc);
    this.update(initialState);
    this.model.view.showTrack(this.model.configuration.sequenceTrack);
```

**Comment by garrettjstevens** [comment]
It shouldn't technically need the assembly manager, but it looks like I missed a check there. Probably something like this needs to happen:
```diff
diff --git a/packages/linear-genome-view/src/BasicTrack/util/serverSideRenderedBlock.js b/packages/linear-genome-view/src/BasicTrack/util/serverSideRenderedBlock.js
index 594d35ff..e18d5e78 100644
--- a/packages/linear-genome-view/src/BasicTrack/util/serverSideRenderedBlock.js
+++ b/packages/linear-genome-view/src/BasicTrack/util/serverSideRenderedBlock.js
@@ -36,9 +36,10 @@ function renderBlockData(self) {
     trackConfParent = getParent(trackConfParent)
   const trackAssemblyName = readConfObject(trackConfParent, 'assemblyName')
   const trackAssemblyData =
-    assemblyManager.assemblyData.get(trackAssemblyName) || {}
+    (assemblyManager && assemblyManager.assemblyData.get(trackAssemblyName)) || {}
   const trackAssemblyAliases = trackAssemblyData.aliases || []
   let cannotBeRenderedReason
```

I'm working on some changes that will abstract this out more so the track won't even have a reference to the assembly manager, it'll just get the info it needs from the session.

**Comment by nathandunn** [comment]
Cool.  Would it be more efficient for me to wait on those changes? 

Nathan

**Comment by cmdcolin** [comment]
I know this doesn't directly address the issue here but this PR seems to suggest that your dev environment is a bit weird (I think opn-cli, setting NODE_ENV=development, should not be necessary. also you appear to be looking directly at the webpacked javascript output instead of the source map). Certainly we will try and fix some of the bugs mentioned here but it would probably be helpful to get you setup with the dev environment properly. Maybe before or after meeting tomorrow?

**Comment by garrettjstevens** [comment]
`open-cli` is actually missing from the devDependencies. Looks like we need to add it.

**Comment by cmdcolin** [comment]
Oh I see. Ok I thought this was a PR for jbrowse-web. The dev environment for the protein widget is different as it tries to just be available via a static index.html. I am not sure I am a big fan of this especially for the developer experience. I think it will be a smoother development cycle if we just include a webpack-dev-server and then make it compile to some components at the end of it.

**Comment by nathandunn** [comment]
@garrettjstevens  worksish with your fix.   Now just getting this:

image

on jbrowse-components/packages/protein-widget/umd.html

Of course this is because I had to disable both the trackAssemblyAliases.    

**@garrettjstevens  Is this going to be easier if I wait for you to finish your stuff, or do you think there is a simple workaround?**

Ideally, I want follow what is best-practices here as a template for folks to create their own widgets.

**Comment by garrettjstevens** [comment]
@nathandunn yeah, I think if you wait for the stuff I'm working on to be done it'll probably be worth it. Hopefully what I'm doing will make it easier to get the protein widget working again.

**Comment by nathandunn** [comment]
@garrettjstevens  Sounds good.   Just let me know when you're done and I'll merge it in to move forward.   Thanks.

**Comment by nathandunn** [comment]
Closing if favor of #413

**Pull request closed without merging**
