### PR TITLE
Config guide updates

### LINKED ISSUE #1638: Add section on FromConfigAdapter/FromConfigSequenceAdapter to docs
It would probably be good to add some docs describing the FromConfigAdapter and FromConfigSequenceAdapter. I could see people making plugins collecting data from APIs finding them really useful. Right now they aren't in the docs.

I think a good spot could be in the config guide.

### PR DESCRIPTION
**Pull request by elliothershberg**
Some updates to the config guide in our docs:

1. Update `WiggleTrack` -> `QuantitativeTrack` to update the name change since the addition of displayTypes
2. Add an "Advanced adapters" section which covers the `FromConfigAdapter` and `FromConfigSequenceAdapter`, and an example of how they might be useful. (Closes #1638 )

### CODE REVIEW

**Comment by cmdcolin** [comment]
Might be worth mentioning some examples of how these look in the config since it is somewhat complicated how QuantitativeTrack interacts with LinearWiggleDisplay and finally an XYPlotRenderer for example

**Comment by cmdcolin** [comment]
Very good to keep these docs in shape though :) thanks

**Comment by elliothershberg** [comment]
> Might be worth mentioning some examples of how these look in the config since it is somewhat complicated how QuantitativeTrack interacts with LinearWiggleDisplay and finally an XYPlotRenderer for example

Yeah, good point. Maybe instead of adding that to this guide, we could add a Storybook story showing how that works, and do #1469 . I know you had some doubts about the usefulness, but this is an example where users could see examples of configuration linked to running output. Also if we do it in a story, it could help with keeping it up to date since updates to the config that weren't compatible would break the story.

**Comment by cmdcolin** [comment]
>Yeah, good point. Maybe instead of adding that to this guide, we could add a Storybook story showing how that works, and do #1469 . I know you had some doubts about the usefulness, but this is an example where users could see examples of configuration linked to running output. Also if we do it in a story, it could help with keeping it up to date since updates to the config that weren't compatible would break the story.

I'm all for it. Any updates on getting the storybook deployed?

**Pull request merged**
