### PR TITLE
Website template

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a template website that could be expanded upon, initialized using docusaurus v2

I thought it would just be worth it to have a template to build on. It could be deployed to jbrowse.org/v2 or similar if there is interest and include expanded documentation, live demos, etc

### CODE REVIEW

**Comment by rbuels** [comment]
OK, let's pause this and keep focused on comparative views if possible. Looking into possibly contracting out the initial build of the new website, but if that doesn't end up happening this could be a good starting point.

**Comment by cmdcolin** [comment]
I revisited using docusaurus as a potential alternative to storybook . Docusaurus can support MDX and since storybook was being held back by mdx dreamin, I thought this would be a good alternative


I made a small monorepo that has

packages/mybutton - a typescript react component with a button
packages/website - docusaurus component that imports mybutton and demos it on an mdx formatted page

This worked pretty nicely https://github.com/cmdcolin/docusaurus_monorepo_demo/

Trying to do a similar thing with jbrowse 2 has been a bit of a battle, maybe related to specialized webpack configuration, but this could conceptually be a nice approach

**Comment by cmdcolin** [comment]
Relevant mdx file https://raw.githubusercontent.com/cmdcolin/docusaurus_monorepo_demo/master/packages/website/docs/mdx.md

**Comment by cmdcolin** [comment]
Fair amount of stuff missing but can start to load the jbrowse app on a page


localhost_3000_docs_mdx

**Comment by cmdcolin** [comment]
Started some of the website design concept on this branch


localhost_3000_ (2)


Feel free to contribute. The template design we have is nice to work with

**Comment by cmdcolin** [comment]
Fleshed out a bit more redesign and added a `yarn deploy` that will manually deploy the code if the aws keys are setup on your machine http://jbrowse.org/jb2/

**Comment by cmdcolin** [comment]
This branch is maybe paused just to make it more targetted for accessibility and I'm going to work on fleshing out docs on a new branch website_docs

For ref here is the template website http://jbrowse.org/jb2/

This branch does not have an auto-deploying travis run, instead relying on a yarn deploy in the packages/website directory

This might be preferable, similar to manually running a yarn publish for an npm package, because I was not thrilled with the [update docs] comment+waiting 45 minutes to run tests in the jbrowse 1 repo

**Comment by cmdcolin** [comment]
By "targetted for accessibility" I mean, a more targetted PR just focused on the homepage basically instead of all the docs that could come along with it

**Pull request merged**
