### PR TITLE
Add ability to customize About dialog with callbacks and optionally hide links to data

### PR DESCRIPTION
**Pull request by cmdcolin**
Adds a `formatAbout` config subschema similar to `formatDetails`

`formatAbout` can be applied per track or at the entire jbrowse config level (so you can add hideUris to the entire jbrowse config)

- The `formatAbout` subschema has a `hideUris` slot to hide the rendering of "UriLocation" objects in the about dialog. Note that the `hideUris` results in the "Copy config" button getting hidden too, since copying to text would reveal this type of hidden info...

- The `formatAbout` subschema also has a `config` slot to add arbitrary jexl callbacks to the display of the config snapshot in the about dialog

Possible fix for https://github.com/GMOD/jbrowse-components/issues/3213

Rider change: makes a getTrackName utility function that computes the track name (the logic for making the "reference sequence track name" was duplicated in several places)

### CODE REVIEW

**Comment by rbuels** [comment]
Is there an extension point that plugins can use to modify the about dialog
as well?  If not, could add one in this

**Comment by cmdcolin** [comment]
Added "Core-customizeAbout" extension point that receives a conf object to customize the contents

**Comment by cmdcolin** [comment]
could be interesting to allow track types or plugins to customize the entirety of the about component, similar to how widgets can be swapped out perhaps

**Comment by carolinebridge-oicr** [comment]
Just curious -- what does the change to getEnv do for us?

**Comment by cmdcolin** [comment]
that was indeed a rider change added to this, but it gives us better typescript (getEnv is returning an `any` type before, and with this change, we import getEnv from @jbrowse/core/util and it gives us a `{pluginManager: PluginManager}`)

**Comment by cmdcolin** [comment]
putting this in draft till some things like https://github.com/GMOD/jbrowse-components/issues/3262  can be resolved.

**Comment by cmdcolin** [comment]
this is now enhanced with a couple more extension points that let you do some relatively crazy things including

a) completely replacing the contents of any widget by responding to Core-replaceWidget
b) completely replacing the contents of the about dialog with Core-replaceAbout
c) adding extra about panels to the about dialog with Core-extraAboutPanel
d) adding extra feature detail panels to the feature details with Core-extraFeaturePanel

in addition, there are the about panel config options for

formatAbout:{ hideUris:boolean, config: "jexl:callback to customize any of the config display" }

this PR is rebased off of #3266 and has examples of doing these things like the volvox example

**Comment by cmdcolin** [comment]
this pr should be ready

Note that this PR now adds a number of new extension points including the ability to add custom react components to the feature details widget and "about track" dialog, or completely replace them with a custom component (the ability to replace the widget can replace ANY widget)

new extension point names

Core-extraFeaturePanel
Core-extraAboutPanel
Core-replaceWidget
Core-replaceAbout
Core-customizeAbout

they are documented in the api_guide

**Comment by cmdcolin** [comment]
tentatively fixes [Core-replaceAbout](https://github.com/GMOD/jbrowse-components/issues/2034)

**Comment by cmdcolin** [comment]
maybe go ahead with a merge, examples of these extension points are in various volvox tracks

**Pull request merged**
