### PR TITLE
Add track menu items to move track to up/down/to top/to bottom, and moving views to top/to bottom

### PR DESCRIPTION
**Pull request by cmdcolin**
this is supplementary to pinning track, I think there is still an opportunity to have these operations without track pinning

see screenshot, since it expands the number of menu items significantly the options are placed under a submenu sort of opaquely named "options"

Screenshot 2024-04-11 at 9 42 35 PM

### CODE REVIEW

**Comment by cmdcolin** [comment]
other options could include making these up/down options on the track label themselves

**Comment by cmdcolin** [comment]
fixes https://github.com/GMOD/jbrowse-components/issues/4315

**Comment by cmdcolin** [comment]
small bonus: by avoiding getSnapshot in the "moveTrack" function (used for click and drag to re-order tracks in the lgv) it avoids the tracks having to re-render themselves

**Review by carolinebridge-oicr — APPROVED** [review]
Tested -- looks and feels good

I feel like "options" isn't the _best_ word for this menu item. Google slides for example uses the word "Order" in their options for moving items to the front/back.

Probably best in another PR but I feel like the click+drag functionality should be updated to be more in line with how intuitive + fluid this feels.

**Comment by cmdcolin** [comment]
agree on the wording being tricky...order is good though!

**Comment by cmdcolin** [comment]
also interestingly, I think the "dimming" of the tracks does not work and was piling up the dimming at the top of the view instead of being dimmed at the right y-offset. removing the dimming may help

**Comment by cmdcolin** [comment]
i've removed the dimming to try to help with that situation for now

**Pull request merged**
