### PR TITLE
Use display:flex to fix SV inspector layout, and fix drag handle

### LINKED ISSUE #667: SV inspector creates side-to-side scrollbar due to uncertain width calculations
If possible, probably best to not try to "manually detect scrollbar presense/absense"...use some CSS flow?

### PR DESCRIPTION
**Pull request by cmdcolin**
This fixes #667 

It uses flexbox layout instead of absolute positioning for the SV inspector

Also the drag handle height was undefined, leading to there being no drag handle, this simply restores that

### CODE REVIEW

**Comment by rbuels** [comment]
If we do this flex layout, how easy is it going to be to put a vertical drag handle between the spreadsheet subview and the circular subview?

**Comment by cmdcolin** [comment]
I added a resize handle (had some trickiness to make it work with flexbox) but it loses focus as soon as you move it...might be a weird react-ism about re-rendering? Any ideas?

**Comment by cmdcolin** [comment]
Fixed the resize handle issue, just needed to properly return the changed size from the resizeWidth action

**Comment by cmdcolin** [comment]
I think the flexbox display is gonna be better than absolute positioning here. If it's ok I'll merge for now :)

**Pull request merged**
