### PR TITLE
Alignments track refactor #2

### PR DESCRIPTION
**Pull request by cmdcolin**
This is additional refactoring that addresses the following needs

1) Designate PileupTrack to be in control of sorting and showing soft clipping, which was till this sort of dependent on being contained in a AlignmentsTrack (RE: #981 )
2) Remove the usage of Sort by being in a view menu, making it a per track option (RE: #982 )
3) Makes it so that the "Show pileup track", "Show coverage track", "Show softclipping" remain with the text "Show" with a checkbox to indicate the status of it being shown (previously toggling between "Show/Hide" which to me can be slightly jarring)

Base branch is alignments_track_refactor to be clear that this adds on to it, but it is basically independant from that branch

### CODE REVIEW

**Comment by peterkxie** [comment]
with track individual sorts, centerLinePosition.tsx showing the active sort option will be broken since it assumes all tracks are sorted at once

**Comment by peterkxie** [comment]
Feature specific and general context menu from right click also seem to be broken on this branch

Currently where ever I right click, it brings up the browser's context menu and then after closing I am in scrolling mode until I click out of the track (moving the mouse without any other mouse events scrolls the track)

**Comment by cmdcolin** [comment]
Thanks I'll check into the right click issue, it appears broken on master but I added a fix in this branch. Can you re-review?

Also


As far as displaying sort status, since it is per-track, I made something I call "track blurb", which is a component that can be set by track type

The PileupTrack has a track blurb, and the alignments track returns self.PileupTrack.TrackBlurb


Looks like this, open to design suggestions or concerns about that

t1

**Comment by cmdcolin** [comment]
@peterkxie I made a couple more changes to how menuOptions for context menu work. It was a little weird to make the SNPCoverage track. I thought I'd just make it so "show pileup track" and "show coverage track" were "Track Menu" only and not context menu and then restore the ability for context menu to work

**Comment by peterkxie** [comment]
I like the track blurb idea + location 

Looks like in your screenshot it is able to read location but when I tried to sort it said undefined:undefined for location
image

The context menu issue looks fixed to me now. Right clicking over a feature opens up a context menu and right clicking outside a feature does nothing which is what I expected after reading your comment

**Pull request merged**
