### PR TITLE
Fix overview polygon bug

### LINKED ISSUE #1096: multi-displayed region LGV polygons bugs
The zoom polygons have some bugs when there are multiple displayed regions. Here, we have all the hg19 chromosomes as displayedRegions, and the polygons are not happy:

image

[Session link](https://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/master/index.html?session=eJydlstu2zAQRX8l4FoJOMO3ti36AIIkqI0mbdEFI41tobZsUGrcIMi_d2QHbopyU-6kIXnmkpxL8kn0cUOiFle0P5vRMHTb_gwlynPpzjHMUdaoa6MuFMJXUYlNTMuuF7WsRJvintJt144rUSuvK_HQ0X4Q9bcn0bWMfHd9RW9lizMe13bDbh0fr47JVksIHBwfd9PfZddTTO-p327oMyO4ZbtYDDTe_BL1OShfifvdDaXpF4x2XvkLJ-0JSu0nWrLuY-pEi5cswKBhjGk8yKWeNaEOaKRFqLjfA6WBOLiI64EqEYeBNvfrvzQ-V6-BmAMqCEE5VQRU_wIheIlMlUVAnQMCLxo6WwQ0GaCXAQzaMoU2A3TAEqV1RUCXAZrAVWNt2ab4DFBbZTXvSxEw5ICAoLh2ioAgM0RljNJOly0iZLzCRCmtgbLCgYxZQClvwAdTRsy5BVhf8M6XEXN2kU7pYHRZdUPOLxKNAhXKigcyhglS8TFoysobMobxAMEgFM45YxjnpXOoC7clYxh2NPrgy6aMGb9YxdtisGzKmLGL9oChtLYx4xYDSmpjy-x3lzsVDTppCs_tL7k94XvvPwR-5xs_xebHdE_z96pr6QPFltJp2J_QNQOn58Sp6TByRmtqxm2aHx8Oq45STM2qa-J6krfa7udTt8t4T2vOMqafdAy_oX6kND00XoCTmH3XLmnkfk_PrLgZuwe6fR1qtn3P6fhl8bHnqfcNHRqefwO-n9lw)

### PR DESCRIPTION
**Pull request by garrettjstevens**
Fixes #1096

### CODE REVIEW

**Comment by garrettjstevens** [comment]
Originally I made this change in packages/linear-genome-view/src/BasicTrack/util/calculateDynamicBlocks.ts, but I realized there was also a calculateDynamicBlocks in core that didn't get the fix. So now this PR also removes calculateDynamicBlocks (and calculateStaticBlocks) from BasicTrack and makes everything use them from core.

**Comment by cmdcolin** [comment]
Could you check if dotplot tolerates this? I didn't unify the Base1DView with linear-genome-view yet because dotplot didn't have padding blocks and such, but it could be an interesting thing to get under one roof

**Comment by garrettjstevens** [comment]
> Could you check if dotplot tolerates this?

I think it should be ok. I added some optional parameters to calculateBlocks to say if there should be padding blocks, and then updated dotplot to use the right options. I also made sure the dotplot image snapshot test didn't change at all.

**Comment by garrettjstevens** [comment]
Not sure why the branch CI build is failing. It doesn't appear to have any errors.

**Comment by cmdcolin** [comment]
I re-ran the CI and it failed again, seemingly at the yarn build step. Running `yarn build` did succeed though...

**Comment by cmdcolin** [comment]
I deleted all repository caches and then re-ran, and it passed. Not sure if related, but is green now

**Comment by cmdcolin** [comment]
Is there a session URL we can use to recreate the issue in #1096?

**Comment by garrettjstevens** [comment]
> Is there a session URL we can use to recreate the issue in #1096?

It's at the bottom of the description of that issue, also [here](https://s3.amazonaws.com/jbrowse.org/code/jb2/alpha/master/index.html?session=eJydlstu2zAQRX8l4FoJOMO3ti36AIIkqI0mbdEFI41tobZsUGrcIMi_d2QHbopyU-6kIXnmkpxL8kn0cUOiFle0P5vRMHTb_gwlynPpzjHMUdaoa6MuFMJXUYlNTMuuF7WsRJvintJt144rUSuvK_HQ0X4Q9bcn0bWMfHd9RW9lizMe13bDbh0fr47JVksIHBwfd9PfZddTTO-p327oMyO4ZbtYDDTe_BL1OShfifvdDaXpF4x2XvkLJ-0JSu0nWrLuY-pEi5cswKBhjGk8yKWeNaEOaKRFqLjfA6WBOLiI64EqEYeBNvfrvzQ-V6-BmAMqCEE5VQRU_wIheIlMlUVAnQMCLxo6WwQ0GaCXAQzaMoU2A3TAEqV1RUCXAZrAVWNt2ab4DFBbZTXvSxEw5ICAoLh2ioAgM0RljNJOly0iZLzCRCmtgbLCgYxZQClvwAdTRsy5BVhf8M6XEXN2kU7pYHRZdUPOLxKNAhXKigcyhglS8TFoysobMobxAMEgFM45YxjnpXOoC7clYxh2NPrgy6aMGb9YxdtisGzKmLGL9oChtLYx4xYDSmpjy-x3lzsVDTppCs_tL7k94XvvPwR-5xs_xebHdE_z96pr6QPFltJp2J_QNQOn58Sp6TByRmtqxm2aHx8Oq45STM2qa-J6krfa7udTt8t4T2vOMqafdAy_oX6kND00XoCTmH3XLmnkfk_PrLgZuwe6fR1qtn3P6fhl8bHnqfcNHRqefwO-n9lw).

**Comment by cmdcolin** [comment]
looks good to me

**Pull request merged**
