### PR TITLE
Add back the RefNameAutocomplete loading state

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a bit of refactoring

It removes some internal state of RefNameAutocomplete which gives it a little more predictable behavior, and basically makes it more like a controlled component.

### CODE REVIEW

**Comment by cmdcolin** [comment]
Xref #1327

**Comment by cmdcolin** [comment]
To expand a little more

The internals of RefNameAutocomplete had a useState and a defaultRegionName which is very similar to an uncontrolled component, and then called useEffect to setSelection to the ImportForm outside it

This led to some weirdness when trying to add a loading state back because it started doing some weird stuff where it would call onSelect  on initialized but then coarseDynamicBlocks wouldn't be updated yet and so if you navigated to ctgB it would snap back to ctgA. This struck me as a pretty weird and so I worked to not make it rely on this initialization-calls-onselect behavior and instead rely on controlled input, and the plain onChange handler

**Comment by garrettjstevens** [comment]
I noticed that with this change, if you enter something that doesn't exist, it shows "Loading..." instead of the "No options" it showed before.

image

vs.

image

**Comment by garrettjstevens** [comment]
oh shoot, I pushed to this branch on accident, I'll revert it

**Comment by cmdcolin** [comment]
no worry. that is a good catch for the loading state also...

**Comment by cmdcolin** [comment]
It's possible uncontrolled component is another pattern but this works well for async fetching the data but this does appear to help with the current use cases of refnameautocomplete

**Pull request merged**
