### PR TITLE
Add a couple nocks for tests

### PR DESCRIPTION
**Pull request by garrettjstevens**
These tests fail on my local machine unless I add these nocks.

### CODE REVIEW

**Comment by cmdcolin** [comment]
http://example.com/ seems like a funny little test domain that actually does give a 200 for any file. This is kinda a funky thing though and illustrates depends on example.com...seems like adding the nocks is good

**Comment by garrettjstevens** [comment]
> http://example.com/ seems like a funny little test domain that actually does give a 200 for any file

That domain doesn't work for me, which must be why it didn't pass on my computer

**Comment by cmdcolin** [comment]
Ha! there we go :)

**Comment by rbuels** [comment]
Or maybe example.com is purposely failure prone :-)

**Pull request merged**
