### PR TITLE
Add logoPath on jbrowse-desktop to fix crash

### PR DESCRIPTION
**Pull request by cmdcolin**
Currently starting up jbrowse desktop crashes because it tries to access a nonexistant logoPath configslot on the desktop's jbrowseModel

This fixes that by adding the logoPath configslot to desktop, plus a couple of items that jbrowse-web has that desktop didn't have  (theme, featureDetails,and ...pluginConfigurationSchemas()) just for good measure

Also makes the Logo a component

### CODE REVIEW

**Comment by rbuels** [comment]
Is there any way we can add a test that would have caught this? cc @elliothershberg @garrettjstevens @cmdcolin

**Comment by cmdcolin** [comment]
Might also be worth reflecting on the causes e.g.

a) no good testing for jbrowse-desktop exists, so this wasn't caught by our testing
b) jbrowse-web and jbrowse-desktop continue to kind of maintain their own pretty related but slightly different set of things

**Comment by garrettjstevens** [comment]
I think it's good to add those other slots to the desktop config, but I'm not sure logoPath makes sense on the desktop. I think changing the logo on the desktop would be part of a more comprehensive "MOD branding toolkit" (as mentioned in the roadmap) that also changes the app icon, start screen logo, etc.

**Comment by cmdcolin** [comment]
what was the purpose of logoPath being merged in the first place? I don't have the context for it.

**Comment by cmdcolin** [comment]
e.g. it seems like it's part of "MOD branding" in general...do you see it differently

**Comment by cmdcolin** [comment]
todo: add a test for opening blank session to check that this doesn't crash e.g. a regression test for this case

**Pull request merged**
