### PR TITLE
Remove "flag helpers" from the BAM/CRAM features

### PR DESCRIPTION
**Pull request by cmdcolin**
- Removes the "flag helpers" from the BAM/CRAM features, emphasizing to use the feature.get('flags') directly
- Reflection on the prototype getters for the BamSlightlyLazyFeatures features, similar to how it is  done for CramSlightlyLazyFeatures
- Use MD and CIGAR capitalized in the codebase, making capitalization sensitivity a bit higher (pre-serialization doesn't toLowerCase)

Note that we could keep the flag helpers if it's helpful for, perhaps, callback writers, but I think it's probably more confusing than helpful.

### CODE REVIEW

**Comment by cmdcolin** [comment]
This is a breakout from the larger branch #1231

**Comment by rbuels** [comment]
probably speeds up serialization and deserialization as well right?

**Comment by cmdcolin** [comment]
I didn't measure time but say you had 10,000 alignments it could save upwards of a megabyte serialized/deserialized

This should probably be pretty fast according to https://surma.dev/things/is-postmessage-slow/ major wait times would be elsewhere most likely

**Comment by cmdcolin** [comment]
My major concern with this branch, as far as motivation, was that @gmod/bam was returning "unmapped", "duplicate", etc from it's "tags()" method incorrectly, because it did not even implement these getters. So that was incorrect. And then as far as this module,  I thought, these are kind of confusing anyways, so I figured why not remove

**Comment by cmdcolin** [comment]
note that there is a specific status message for serialization so if that was ever taking too long, we would probably notice and report a bug

**Pull request merged**
