### PR TITLE
Add ability to minimize/collapse tracks and views and move views up/down in view stack

### LINKED ISSUE #535: reorder views in main area
We need a way to reorder the views in the main area.

### PR DESCRIPTION
**Pull request by cmdcolin**
This adds the ability to toggle a "minimize" a track. The track is then not visible. This can be useful because closing a track or view loses it's state entirely, while minimizing will keep it the track state available

The text "(minimized)" is appended to track labels when this state is enabled

Fixes https://github.com/GMOD/jbrowse-components/issues/2531
Fixes https://github.com/GMOD/jbrowse-components/issues/2107
Fixes #535

Screenshot from 2022-11-15 09-12-54

### CODE REVIEW

**Comment by cmdcolin** [comment]
moved the minimize button for track into the track menu, so looks like this now

Screenshot from 2022-11-15 09-25-13

**Comment by cmdcolin** [comment]
Also adds ability to move view up/down in the view stack also now

Screenshot from 2022-11-15 10-05-08

could possibly add drag but that can be tricky to implement (and also to use, if views are especially tall for example)

**Comment by cmdcolin** [comment]
(can also see from screenshot, the view menu item list is getting a bit large. could consider ways to try to reduce size?)

**Comment by garrettjstevens** [comment]
It's really nice to have these functionalities added. I would like, though, to discuss the possibility of adjusting some of the terminology and icons. To me, "minimize" (and the minimize icon) implies moving the view/track entirely (like minimizing an OS window to the panel). I propose using "collapse" and "expand" instead of "minimize" and "restore," and using the "ExpandMore" and "ExpandLess" icons.

image
image

**Comment by cmdcolin** [comment]
not sure if we came to conclusion about the minimize/expand collapse. 

I personally like the intuitive meaning of the "-" icon especially where the - icon is next to the x in the view header since that is just a common UI concept to me. for the track label, where it is inside the track menu, the icon is not as important probably

**Comment by cmdcolin** [comment]
i think later on, it might even make sense to make a 'minimized drawer' type zone..the current minimized implemented here is a little intrusive/prominent while a true minimize might want to go away a little more. despite it being more like a collapse now, i think sticking with the current icon scheme would be my preference :)

**Pull request merged**
