### PR TITLE
Add free resources

### PR DESCRIPTION
**Pull request by cmdcolin**
This implements the freeResources function for serverSideRenderedBlock using the beforeDestroy method

Then it wires up rpc calls to freeResources for the renderer (which performs discardRange) and the data adapters

It also performs serialize region to only send features relevant to a region to the client for things like pileup renderer (see #229). The logic here is that instead of not sending the layout, we just try to optimize the layout that is sent, because not sending the layout could incur some trouble (e.g. makes mouseovers more difficult or similar)

Feel free to test this out and let me know how it works

### CODE REVIEW

**Comment by cmdcolin** [comment]
Appears to cause problems with svg features quite prominently. Will need to investigate more

**Comment by cmdcolin** [comment]
The goodnews of course is that, perhaps if we dig deep enough, some of the other SVG feature rendering bugs might come into focus...

**Comment by cmdcolin** [comment]
Ref #327 #270

**Comment by cmdcolin** [comment]
I updated this to include the #370 fix and I think the serializeRegion for the layout needs to be aware of the maxFeatureGlyphExpansion, because otherwise it will not serialize relevant layout features

**Comment by rbuels** [comment]
let just merge this so things don't get too branchy

**Pull request merged**
