### PR TITLE
Small Improvements to create and upgrade testing

### PR DESCRIPTION
**Pull request by peterkxie**
changes by @garrettjstevens to improve the test files of create and upgrade. Instead of having nock persist, nock is called during the setup of each test. also fixes an EISDIR error by watching for just file entries and making directories based off file locations

### CODE REVIEW

**Comment by cmdcolin** [comment]
>also fixes an EISDIR error by watching for just file entries and making directories based off file locations

What is the EISDIR error

**Comment by peterkxie** [comment]
He was running into this issue on his machine when running JBrowse create, heres what he sent me on gitter about it:

- Bug fix for occasional Error: EISDIR: I think sometimes it was trying to write a file when the directory hadn't been created yet. To fix that, I just watched for "File" entries and ignored "Directory", making directories based off the file locations instead.

**Comment by cmdcolin** [comment]
Gotcha. Let's merge

**Comment by cmdcolin** [comment]
I will note that I am still surprised that we have to "manually unzip" the zip file, that there is not something that automatically does this...

**Pull request merged**
