### PR TITLE
A few bugfixes

### PR DESCRIPTION
**Pull request by garrettjstevens**
These are just a few bugfixes I've run into that didn't really fit in any particular PR

### CODE REVIEW

**Comment by cmdcolin** [comment]
Why e12cb4d?

**Comment by garrettjstevens** [comment]
> Why e12cb4d?

It broke when the feature had an attribute that was an array of objects. I think specifically it broke because one of the properties of an object was an empty array, and `String([]) === ''`

**Comment by cmdcolin** [comment]
I think that explains the commit e2e10e8 but I was curious about the change to passing the adapters instead of snapshots

https://github.com/GMOD/jbrowse-components/commit/e12cb4d15c3551f833f060e2d3a19528e69051a2

**Comment by garrettjstevens** [comment]
Whoops, mixed up to commit ids. That's to match the behavior of creating an adapter in `packages/core/data_adapters/dataAdapterCache.ts`. `readConfObject` does a `getSnapshot` on the config, and the configs have a snapshot processor that strips out default values, so there can be cases where the thing you want gets stripped out before being used in the adapter constructor.

**Comment by cmdcolin** [comment]
gotcha. basically this is not using data adapter cache and so getting a snapshot of it there is not appropriate. basically fallout from https://github.com/GMOD/jbrowse-components/pull/1438 then...

could you add a short comment about that there to explain this subtle change

**Comment by cmdcolin** [comment]
just went ahead and added a comment here, probably good to go:)

**Comment by garrettjstevens** [comment]
> just went ahead and added a comment here, probably good to go:)

Thanks!

**Comment by rbuels** [comment]
good to merge as soon as conflicts are resolved

**Comment by cmdcolin** [comment]
```
        if (!self.tracks.length) {
          self.connect(self.configuration)
        }

```

What case was seen when there is self.tracks and we avoid calling self.connect

**Comment by garrettjstevens** [comment]
> What case was seen when there is self.tracks and we avoid calling self.connect

This is for when a session that has a connection is restored from a snapshot. Currently when the session is restored it re-fetches all the tracks, and this avoids that.

The way our connections in core are written they use `setTrackConfs`, which overwrites the existing tracks with the newly fetched ones. But connections don't have to do that. If they used e.g. `addTrackConf` instead, without this change you would end up with duplicate tracks in your connection when you refreshed the page (which is how I originally noticed this bug).

**Comment by cmdcolin** [comment]
>This is for when a session that has a connection is restored from a snapshot. Currently when the session is restored it re-fetches all the tracks, and this avoids that.

What if the connection has thousands of tracks? Are these all serialized into session?

**Comment by cmdcolin** [comment]
Or alternatively, shouldn't re-fetching tracks on startup actually be the right thing to do for a connection?

**Comment by garrettjstevens** [comment]
> What if the connection has thousands of tracks? Are these all serialized into session?

Yes, similar to session tracks, they are in the session.

> shouldn't re-fetching tracks on startup actually be the right thing to do for a connection?

I thought the intended behavior was to have the connection re-fetch tracks only if it was closed and re-opened again, but if that doesn't sound right we can discuss it.

**Comment by cmdcolin** [comment]
My intuitive feeling is that the connection tracks should be refetched or refresh of the page, however, a complication is how this interplays with having a track opened from a connection and then refreshing: That means that that track would fail to resolve its configuration reference if the track wasn't in the session

**Comment by rbuels** [comment]
merge when ready

**Review by rbuels — APPROVED** [review]
adding an explicit green checkmark ;-)

**Pull request merged**
