### PR TITLE
Desktop and adminMode delete and copy track functions

### PR DESCRIPTION
**Pull request by cmdcolin**
This uses ideas from the session tracks to give desktop the ability to delete and copy tracks

Also addresses #1295 

Note that somehow maybe this PR exaggerated #1295 and then fixed it e.g. before this commit a291322 this branch was painfully slow. Desktop LGV scrolling was actually ok on master...

### CODE REVIEW

**Comment by cmdcolin** [comment]
This PR may want to also consider adminMode web delete and copy tracks

**Comment by cmdcolin** [comment]
Note: In order to fix #1280, I detect whether the trackId.endsWith('sessionTrack') instead of checking session.sessionTracks which desktop does not have

**Comment by cmdcolin** [comment]
The ability to delete connections was added as a rider to this PR

Another fix was done to allow accessing COSMIC files. This required augmenting the openUrl and changing the check for isElectron for the rangeFetcher. Note that NCList does not use generic-filehandle openLocation so the openUrl needed this logic.

**Comment by cmdcolin** [comment]
@elliothershberg would you want to test this under admin mode, the ability to copy and delete tracks

**Comment by elliothershberg** [comment]
> @elliothershberg would you want to test this under admin mode, the ability to copy and delete tracks

Yeah I can test this

**Comment by elliothershberg** [comment]
@cmdcolin I can delete and copy tracks in admin mode from this branch 👍 

Randomly, for some reason, two tests fail when I run the test suite locally on this branch, although it doesn't seem to be an issue on Travis

**Comment by cmdcolin** [comment]
@elliothershberg which tests? there are occaisionally some that fail locally for me also. namely zoom in and out. always chalked it up to a timeout thing but could be worth making a housekeeping issue

**Comment by elliothershberg** [comment]
image

I get a snapshot fail from alignments, and intermittently the dotplot test fails locally which is already known #1221

**Pull request merged**
