### PR TITLE
Improve dotplot label collision avoidance

### LINKED ISSUE #921: improve dotplot label drawing
Dotplot axis labels currently draw all over each other, let's find a way to make them look nice.

image

### PR DESCRIPTION
**Pull request by garrettjstevens**
This works by checking if there are going to be colliding labels, and if there are, it starts hiding labels of the smallest blocks first until there are no more collisions. This seems to successfully label "more important" (i.e. bigger) regions over smaller ones

image

Resolves #921

### CODE REVIEW

**Comment by rbuels** [comment]
lot of iterations and array copying, is the performance OK?

**Comment by garrettjstevens** [comment]
It seemed ok when I was scrolling around, but in any event, I think I have a better idea that I'm going to try.

**Comment by garrettjstevens** [comment]
Ok, a lot less iteration now and overall I think a lot simpler. Instead of removing the smallest regions, this adds labels for the regions starting with the biggest, skipping ones that have a collision detected. Also has the advantage of still labeling things as much as possible, even when the regions are small.

Before:
image

After:
image

**Comment by rbuels** [comment]
Ah that is an elegant way to do it

**Comment by cmdcolin** [comment]
looks sharp to me! I say merge it. I am glad to see more tinkering with the dotplot code :)

**Pull request merged**
