### PR TITLE
Add flag to text-index cli subcommand to create text-index for embedded mode

### PR DESCRIPTION
**Pull request by teresam856**
WIP:  In this PR [issue 2282](https://github.com/GMOD/jbrowse-components/issues/2282)
Adds support to index single or multiple files without the need for a config.json
Adds support to index files for embedded mode

TODO:
- [ ] support local files
- [ ] better guess for adapter from filenames
currently using similar logic to guess adapter from add assembly
- [ ] refactor index driver

### CODE REVIEW

**Comment by teresam856** [comment]
Note:  this will most likely delay the release of text-searching
Other discussiona found here [Update trix to return the matched search term if it is not part of the label](https://github.com/GMOD/jbrowse-components/pull/2289)

**Comment by cmdcolin** [comment]
maybe we push back release day to tomorrow or something? or we can release without this pr, probably ok too

**Comment by teresam856** [comment]
> maybe we push back release day to tomorrow or something? or we can release without this pr, probably ok too

I am ok with releasing without this PR.  However, this PR introduces a small change to the meta.json. Do we want to wait to get the label enhancements merged?

**Comment by cmdcolin** [comment]
#2289 (label enhancement) likely won't be done yet. I'm not confident in the trix-js code underlying it yet so it is draft and we could release without it

**Comment by teresam856** [comment]
Ok, I think we can go ahead with the release then.

**Comment by teresam856** [comment]
Closing, this is getting addressed in https://github.com/GMOD/jbrowse-components/pull/2303

**Pull request closed without merging**
