### PR TITLE
Fix uncaught promise errors and add lint rule for catching these

### PR DESCRIPTION
**Pull request by cmdcolin**
This PR fixes, amongst other things, some uncaught promise errors. for example, an error pointed out by @scottcain here is currently an uncaught promise on main https://gitter.im/GMOD/jbrowse2?at=638666984fee72663c9a4ea6

This also adds a lint rule no-floating-promises, which is very good at catching code that would cause "Uncaught promise" errors so there are many changes related to this https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md

### CODE REVIEW

**Comment by cmdcolin** [comment]
cc @garrettjstevens possibly a good rule to have turned on :)

surprised it wasn't part of     "plugin:@typescript-eslint/recommended" which i believe we already had

**Comment by cmdcolin** [comment]
realized that it's not on by default probably because it requires type checking so would be part of e.g.  

    "plugin:@typescript-eslint/recommended-requiring-type-checking"

**Comment by garrettjstevens** [comment]
> cc @garrettjstevens possibly a good rule to have turned on for apollo :)

For sure, thanks. I've started a branch with `@typescript-eslint/recommended-requiring-type-checking` here: https://github.com/GMOD/Apollo3/tree/eslint-typecheck.

**Comment by cmdcolin** [comment]
nice...for jbrowse-components, turning on the recommended-requiring-type-checking produces about ~7000 warnings mostly due to use of the "`any`" type. could be a good thing, but would probably require a lot of casts to just sort of make the warnings go away, still can help ensure expectations though

**Pull request merged**
