### PR TITLE
Fixes crash after importing bookmarks via TSV

### PR DESCRIPTION
**Pull request by carolinebridge**
Fixes crash after importing bookmarks via TSV by filtering out the header in the import operation; addresses https://github.com/GMOD/jbrowse-components/issues/4359

### CODE REVIEW

**Comment by cmdcolin** [comment]
what if we only made it so that users exported BED and not TSV to avoid confusion about TSV vs BED?

**Comment by carolinebridge** [comment]
I don't really think it's a problem to have both. This bug was discovered presumably because a user is using the TSV format.

**Comment by cmdcolin** [comment]
on some level, the problem is sort of that the import form doesn't have a "toggle" to control whether you are importing a TSV or BED type

it only is working with this PR because the TSV is so similar to the BED type

If we just had BED, then we wouldn't necessarily have this bug, and the user also would not have to think about the difference between TSV and BED

**Comment by carolinebridge** [comment]
I can change the PR to remove the TSV support if you think that better addresses the issue

**Comment by cmdcolin** [comment]
I thought about it a bit and maybe keeping tsv can be ok. it is just the only workflow that bulk imports from a single file. In the new PR I added extra UI to the import form to let the user select TSV or BED, but i hope by making it explicit what format is being imported, it avoids potential issues https://github.com/GMOD/jbrowse-components/pull/4362

**Pull request closed without merging**
