### PR TITLE
Virtualized tree for tracklist to support having thousands of tracks

### LINKED ISSUE #728: support having thousands of tracks
Having thousands of tracks introduces some issues of scale. We may need react-window to reduce number of dom elements in track selector, or we may see mobx-state-tree performance issues, or other unexpected things

Create something like modencode test dataset, or larger

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a draft PR for using a virtualized tree for large tracklist rendering

Demos

volvox
http://s3.amazonaws.com/jbrowse.org/code/jb2/virtualized_tree/index.html?config=test_data%2Fvolvox%2Fconfig.json

1000 genomes data
http://s3.amazonaws.com/jbrowse.org/code/jb2/virtualized_tree/index.html?config=https%3A%2F%2Fs3.amazonaws.com%2Fjbrowse.org%2Fgenomes%2FGRCh38%2F1000genomes%2Fconfig_1000genomes.json&session=share-SUK-mntGyB&password=eQF0F

Todos include restoring "Add track" and "Add connection" button, adding the "track actions" (...) after tracks, and possible user-interface prettying

Any early feedback welcome

Probably we will not have text wrapping as a compromise for simplicity, and we will have a slightly side-scrollable list

Fixes #728

### CODE REVIEW

**Comment by cmdcolin** [comment]
I got some progress on this, it takes a lot of work to get everything right but it works in both react-linear-genome-view and jbrowse-web/desktop

I tried with both plain input type="checkbox" and mui checkbox

It turned out that MUI checkboxes are inherently slow. This is sort of not that surprising because the slowness of MUI checkboxes is what led us to make this solution listed here


MUI checkbox screenshot

localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-YzjUh8IyD (1)


Native checkbox screenshot

localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-YzjUh8IyD (2)


I believe it may be worth dropping to native inputs, as it has improved performance and is aesthetically not bad looking. There is a real and visible performance hit to using MUI checkboxes, and this is well known (google mui checkbox performance, the AGR actually ran into this in 2016 and dropped material-ui entirely https://github.com/alliance-genome/agr_archive_initial_prototype/issues/36 https://github.com/mui-org/material-ui/issues/3289)

Note that the BaseFeatureDetails for example has sparring use of MUI, so maybe it is not really required to use MUI for 100% of everything

**Comment by cmdcolin** [comment]
Other design notes:
- instead of float:right on the ... menu, it is right next to the track label, it is difficult to properly float right in the virtualized area
- the width of the virtualized area is actually dynamic according to the width of the largest track label
- the connection switch/toggles are moved into a hamburger menu next to the filter box, and similarly instead of tabs for multiple assemblies in the tracklist into a dropdown submenu in the hamburger menu. if no connections or multiple assembly situation exists in the tracklist, then the hamburger menu is not rendered to just avoid confusion about an empty menu
- there is now a "manage connections" dialog box used for deleting connections completely, so that the hamburger can be used just for toggling connections on and off, and the "manage connections" dialog can delete them
- the react-linear-genome-view uses a Dialog instead of a Modal for the widgets now, the previous use of modal seemed to be simulating a dialog but now it's just a true dialog and I set it to maxWidth "xl"
- use of AutoSizer is pretty difficult to get right, but does work here in both the drawer and the react-linear-genome-view Dialog context. it has to subtract the height of the header bars using a getClientBoundingRect measurement. I'd be curious in testing to see if this behaves correctly on other's machines, basically you want to see just a single scroll bar for the virtualized scroll area instead of the virtualized area overflowing the drawer, resulting in a scrollbar for the drawer and a scrollbar for the virtualized area (which could be overcome perhaps by overflow:hidden on the drawer, but probably worth figuring it out without the crutch still)

**Comment by cmdcolin** [comment]
Screenshot of a "manage connections" workflow just showing how to delete a connection

out-fs8

**Comment by cmdcolin** [comment]
Here is virtualized tree with MUI checkboxes
http://s3.amazonaws.com/jbrowse.org/code/jb2/virtualized_tree/index.html?config=https%3A%2F%2Fs3.amazonaws.com%2Fjbrowse.org%2Fgenomes%2FGRCh38%2F1000genomes%2Fconfig_1000genomes.json&session=share-SUK-mntGyB&password=eQF0F

Here is virtualized tree with native checkboxes
http://s3.amazonaws.com/jbrowse.org/code/jb2/virtualized_tree_plain_inputs/index.html?config=https%3A%2F%2Fs3.amazonaws.com%2Fjbrowse.org%2Fgenomes%2FGRCh38%2F1000genomes%2Fconfig_1000genomes.json&session=share-SUK-mntGyB&password=eQF0F

now that I look at the production versions, it might not be so bad of a difference, but in dev, it seems like it is noticeable

**Comment by cmdcolin** [comment]
Possible improvement, using the same coloring on category headers as on master

localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-27_J5Ttju

still looks a little less polished but does give a better impression of what the categories are

**Comment by cmdcolin** [comment]
Did a bit more hacking on the look and feel

I think it feels fairly similar to the main branch, just the accordions are not outlined. I would probably double take if someone told me it looked different now :)

Example:

localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-NbZlESMzO


It uses the VariableSizeTree now instead of FixedSizeTree so that "accordion" headings are a bit larger than the others, and tries to style them similarly with vertical text centering for those nodes, small extra margin, etc

**Comment by cmdcolin** [comment]
demo with 1000 genomes http://s3.amazonaws.com/jbrowse.org/code/jb2/virtualized_tree/index.html?config=https%3A%2F%2Fs3.amazonaws.com%2Fjbrowse.org%2Fgenomes%2FGRCh38%2F1000genomes%2Fconfig_1000genomes.json&session=share-SUK-mntGyB&password=eQF0F

demo on human instance http://s3.amazonaws.com/jbrowse.org/code/jb2/virtualized_tree/index.html?config=test_data%2Fconfig_demo.json&session=share-UkFYdJ9r1B&password=ZI3H7

**Comment by cmdcolin** [comment]
I made another contribution to this branch to try to keep main branch styling

We don't get a full box around each nested level like the accordion from main branch, but in this new branch I have added "repeated tick markers" to indicate depth. I think the effect is basically the same, and you can easily see what depth of the tree you are at

Ref
localhost_3000__config=test_data%2Fconfig_demo json session=local-RUmIQvUZq (2)

**Comment by rbuels** [comment]
this is getting pretty polished, any reason this is still a draft? it's a big performance win I think.

**Comment by cmdcolin** [comment]
I wanted someone to do a once over before it was marked "green" (since it seems like green is ready to merge)

Feel free to just try usability here  

http://s3.amazonaws.com/jbrowse.org/code/jb2/virtualized_tree/index.html?config=test_data%2Fconfig_demo.json&session=share-UkFYdJ9r1B&password=ZI3H7

http://s3.amazonaws.com/jbrowse.org/code/jb2/virtualized_tree/index.html?config=https%3A%2F%2Fs3.amazonaws.com%2Fjbrowse.org%2Fgenomes%2FGRCh38%2F1000genomes%2Fconfig_1000genomes.json&session=share-SUK-mntGyB&password=eQF0F

**Comment by cmdcolin** [comment]
Just went ahead and marked as green :) welcome to review can change back to draft if there are outstanding concerns

**Comment by rbuels** [comment]
comments from grooming just now:

* split current hamberder menu into two: connections and assemblies, each with their own icon
* add "add connection" to the connections dropdown menu so we never have to disable it
* keep hiding the assemblies menu when not available

**Comment by cmdcolin** [comment]
I tried adding a connection icon

Screenshot
localhost_3000__config=test_data%2Fconfig json session=local-YG9LjO4to (2)


I guess while it satisfies the outline we made in the previous comment, I feel like the ux is still a bit weird. I put it on a separate branch for now. My feeling is that it is a bit better without. My reasoning is that hamburger menu fits user expectation better, people who are interested can locate a hamburger menu, but for the 99% of users it does not concern them as much

Can try it out here once the codes are built

http://s3.amazonaws.com/jbrowse.org/code/jb2/virtualized_tree/index.html?config=test_data%2Fconfig.json&session=share-UkFYdJ9r1B&password=ZI3H7


http://s3.amazonaws.com/jbrowse.org/code/jb2/virtualized_tree_connect_icon/index.html?config=test_data%2Fconfig.json&session=share-UkFYdJ9r1B&password=ZI3H7

**Comment by cmdcolin** [comment]
I went ahead and merged the power icon drop down for the connections after talked with @elliothershberg 

It now also pops up a dialog to toggle connections on and off

The space was too cramped I think to properly toggle them via a submenu of that dropdown and any reasonably long connection name would go offscreen

**Comment by cmdcolin** [comment]
The connection tracks are also loaded into a separate tree root (mentioned on call) so that the connection tracks live in a separate hierarchy from the rest of the tracks now

Here is a small gallery

t1
t5

t3
t4

**Comment by elliothershberg** [comment]
I'm looking over this now after pairing with @cmdcolin and thinking about any feedback from a usability perspective. I think overall, as @rbuels pointed out, this is a big performance win as track lists scale.

A few smaller details:

1. The floating "+" button could probably get bumped up a little bit, it bumps against the scroll bar that shows up for me (tiny pixel pushing detail 😆)

image

2. In the dialog boxes, is it redundant to have the close button and the "x" icon in the top right?

3. Does this implementation require having the new top level tracks part of the hierarchy?

image

vs.

image

On that note, would it possible to give a little bottom margin to the individual sections so that there is a bit more breathing room between things? If it would be hacky to implement, might not be worth it.

Those are the only small points I have on the UI. Always good to improve performance 💪

**Comment by cmdcolin** [comment]
1. can do
2. I think the duplication shouldn't be too bad...there are just three ways to close dialog (X icon, Close button, clicking outside the dialog....kinda silly but shouldn't cause too much cognitive overhead)
3. While I understand there is a design difference here, I think it may be good to keep the "Tracks" hierarchy, because it allows you to actually collapse all of the main "Tracks", and then only expand connection tracks. see above screenshot https://user-images.githubusercontent.com/6511937/114908911-90ab8500-9dea-11eb-8670-5b98a903ec19.png

**Pull request merged**
