### PR TITLE
Hide add track and connection menu items when using embedded component

### PR DESCRIPTION
**Pull request by carolinebridge-oicr**
Removes the ability to attempt to add a track or connection when using an embedded component. The UI is hidden based on the existence of the session.addTrackConf property.

resolves https://github.com/GMOD/jbrowse-components/issues/1634 and part of https://github.com/GMOD/jbrowse-components/issues/2516

### CODE REVIEW

**Comment by cmdcolin** [comment]
The toggling depending overrideDimensions is a little bit of a hidden behavior, and could probably change in the future, it was sort of a short stop to allow better dialog width/height for the widgets for embedded components.

 It might be good to explicitly hide things based on whether session.addTrack exists perhaps?

**Comment by cmdcolin** [comment]
this looks good. I think technically one more thing is that it hides ability to toggle connection on/off and i believe connections are not entirely disabled in the embedded view (e.g. makeConnection, connectionInstances are in the react-linear-genome-view createSessionModel) it might be useful to keep that option, toggling on session.makeConnection

**Comment by carolinebridge-oicr** [comment]
> this looks good. I think technically one more thing is that it hides ability to toggle connection on/off and i believe connections are not entirely disabled in the embedded view (e.g. makeConnection, connectionInstances are in the react-linear-genome-view createSessionModel) it might be useful to keep that option, toggling on session.makeConnection

I'm getting `session.addConnectionConf is not a function` when I attempt to create a connection on embedded, oversight?

**Comment by cmdcolin** [comment]
There is addConnectionConf to add a new connection configuration, but the ability to turn on/off connections (makeConnection/breakConnection) is in the track selector too and I believe embedded has this

**Comment by cmdcolin** [comment]
nice, I think this is good to go!

**Pull request merged**
