### PR TITLE
Add a VCF side drawer and VariantTrack type

### PR DESCRIPTION
**Pull request by cmdcolin**
This creates a simple side drawer for the VariantTrack type

localhost_3000_ (1)

The genotype/samples table can be very information dense, potentially contain many columns, so this is a struggle for the drawer. I welcome ideas for this. Possible ideas include: displaying one column at a time...filtering on sample, etc.

### CODE REVIEW

**Comment by garrettjstevens** [comment]
I noticed if I click on a variant feature and then click on a different variant feature, the drawer widget doesn't update.

I feel like the INFO attributes should be distinguished from REF, ALT, and QUAL, maybe by indenting a few pixels or something, but maybe that's because I'm so used to looking at VCFs that it's what I expect. Perhaps that wouldn't make sense to other people.

As for the samples table, for now just maybe make it horizontally and vertically scrollable separate from the rest of the drawer? It's a tough problem. Eventually maybe we can make some sort of filter for the FORMAT attributes, but I'm not sure we need it now.

I tested with the following human VCF, and it takes ~1.5 seconds for the drawer to appear after click with 1094 samples. We might have to lazy-load the samples table eventually, but for now I think it's ok. Maybe putting the number of samples in the samples section header would be useful, though (like `Samples (1094)` or something).
https://1000genomes.s3.amazonaws.com/phase1/analysis_results/consensus_call_sets/indels/ALL.wgs.VQSR_V2_GLs_polarized.20101123.indels.low_coverage.genotypes.vcf.gz

**Comment by cmdcolin** [comment]
@garrettjstevens  Thanks for catching this issue where it's not updating? Are there any good tools to debug the thing where it is not updating?

**Comment by garrettjstevens** [comment]
I don't know about a general tool to debug, but I looked at it and figured out what was wrong. I could see that `setFeatureData()` was getting called, but the drawer wasn't updating. Since the underlying data was changing but it wasn't re-rendering, I figured it must not be watching the state properly. I wrapped the `VariantCoreDetails`, `VariantAttributes`, and `VariantSamples` components in VariantFeatureDrawerWidget.js in mobx-react's `observer`, and that seems to have made it work. Another option is to unpack the model in the `VariantFeatureDetails` top-level component and then just pass the needed pieces down to the other components as props.

**Comment by cmdcolin** [comment]
@garrettjstevens thank you so much...makes perfect sense. I dunno exactly how much unpacking I'd have to do so I just went with wrapping it all in observers.

**Comment by cmdcolin** [comment]
I have a weird flaky test on this branch that I'd like to fix...

Already posted this in gitter but when it fails, I am able to "find the svg feature" and click on it, but it doesnt produce the sidebar element and the test fails. I can get to happen with a manually inserted timeout, the SVG looks different in a console log when it succeeds vs when it fails



```
Not working

    SVGElement {
      [Symbol(SameObject caches)]:
       [Object: null prototype] {
         attributes:
          NamedNodeMap {
            '0': Attr {},
            '1': Attr {},
            '2': Attr {},
            '3': Attr {},
            '4': Attr {},
            '5': Attr {} },
         childNodes: NodeList {} } }



Working

    SVGElement {
      '__reactInternalInstance$qj5vpdozs8j':
       FiberNode {
         tag: 5,
         key: null,
         elementType: 'rect',
         type: 'rect',
         stateNode: [Circular],
         return:
          FiberNode {
            tag: 5,
            key: null,
            elementType: 'g',
            type: 'g',
            stateNode: [SVGElement],
            return: [FiberNode],
            child: [Circular],
            sibling: null,
            index: 0,
            ref: null,
            pendingProps: [Object],
            memoizedProps: [Object],
            updateQueue: null,
            memoizedState: null,
            contextDependencies: null,
            mode: 0,
            effectTag: 0,
            nextEffect: null,
            firstEffect: null,
            lastEffect: null,
            expirationTime: 0,
            childExpirationTime: 0,
            alternate: [FiberNode],
            actualDuration: 0,
            actualStartTime: -1,
            selfBaseDuration: 0,
            treeBaseDuration: 0,
            _debugID: 7716,
            _debugSource: [Object],
            _debugOwner: [FiberNode],
            _debugIsCurrentlyTiming: false,
            _debugHookTypes: null },
         child: null,
         sibling:
          FiberNode {
            tag: 0,
            key: null,
            elementType: [Function],
            type: [Function],
            stateNode: null,
            return: [FiberNode],
            child: [FiberNode],
            sibling: null,
            index: 1,
            ref: null,
            pendingProps: [Object],
            memoizedProps: [Object],
            updateQueue: null,
            memoizedState: null,
            contextDependencies: null,
            mode: 0,
            effectTag: 1,
            nextEffect: null,
            firstEffect: null,
            lastEffect: null,
            expirationTime: 0,
            childExpirationTime: 0,
            alternate: [FiberNode],
            actualDuration: 0,
            actualStartTime: -1,
            selfBaseDuration: 0,
            treeBaseDuration: 0,
            _debugID: 7718,
            _debugSource: [Object],
            _debugOwner: [FiberNode],
            _debugIsCurrentlyTiming: false,
            _debugHookTypes: null },
         index: 0,
         ref: null,
         pendingProps:
          { title: 'vcf-2560',
            x: 0,
            y: 0,
            width: 20,
            height: 10,
            style: [Object],
            onMouseDown: [Function],
            onMouseEnter: [Function],
            onMouseOut: [Function],
            onMouseOver: [Function],
            onMouseUp: [Function],
            onMouseLeave: [Function],
            onMouseMove: [Function],
            onClick: [Function],
            onFocus: [Function],
            onBlur: [Function] },
         memoizedProps:
          { title: 'vcf-2560',
            x: 0,
            y: 0,
            width: 20,
            height: 10,
            style: [Object],
            onMouseDown: [Function],
            onMouseEnter: [Function],
            onMouseOut: [Function],
            onMouseOver: [Function],
            onMouseUp: [Function],
            onMouseLeave: [Function],
            onMouseMove: [Function],
            onClick: [Function],
            onFocus: [Function],
            onBlur: [Function] },
         updateQueue: null,
         memoizedState: null,
         contextDependencies: null,
         mode: 0,
         effectTag: 0,
         nextEffect: null,
         firstEffect: null,
         lastEffect: null,
         expirationTime: 0,
         childExpirationTime: 0,
         alternate:
          FiberNode {
            tag: 5,
            key: null,
            elementType: 'rect',
            type: 'rect',
            stateNode: [Circular],
            return: [FiberNode],
            child: null,
            sibling: [FiberNode],
            index: 0,
            ref: null,
            pendingProps: [Object],
            memoizedProps: [Object],
            updateQueue: null,
            memoizedState: null,
            contextDependencies: null,
            mode: 0,
            effectTag: 4,
            nextEffect: [FiberNode],
            firstEffect: null,
            lastEffect: null,
            expirationTime: 0,
            childExpirationTime: 0,
            alternate: [Circular],
            actualDuration: 0,
            actualStartTime: -1,
            selfBaseDuration: 0,
            treeBaseDuration: 0,
            _debugID: 7717,
            _debugSource: [Object],
            _debugOwner: [FiberNode],
            _debugIsCurrentlyTiming: false,
            _debugHookTypes: null },
         actualDuration: 0,
         actualStartTime: -1,
         selfBaseDuration: 0,
         treeBaseDuration: 0,
         _debugID: 7717,
         _debugSource:
          { fileName:
             '/home/cdiesh/src/jbrowse-components/packages/jbrowse-web/src/plugins/SvgFeatureRenderer/components/Box.js',
            lineNumber: 225 },
         _debugOwner:
          FiberNode {
            tag: 1,
            key: 'vcf-2560',
            elementType: [Function],
            type: [Function],
            stateNode: [Box],
            return: [FiberNode],
            child: [FiberNode],
            sibling: null,
            index: 0,
            ref: null,
            pendingProps: [Object],
            memoizedProps: [Object],
            updateQueue: null,
            memoizedState: null,
            contextDependencies: null,
            mode: 0,
            effectTag: 5,
            nextEffect: [FiberNode],
            firstEffect: null,
            lastEffect: null,
            expirationTime: 0,
            childExpirationTime: 0,
            alternate: [FiberNode],
            actualDuration: 0,
            actualStartTime: -1,
            selfBaseDuration: 0,
            treeBaseDuration: 0,
            _debugID: 7715,
            _debugSource: [Object],
            _debugOwner: [FiberNode],
            _debugIsCurrentlyTiming: false,
            _debugHookTypes: null },
         _debugIsCurrentlyTiming: false,
         _debugHookTypes: null },
      '__reactEventHandlers$qj5vpdozs8j':
       { title: 'vcf-2560',
         x: 0,
         y: 0,
         width: 20,
         height: 10,
         style: { fill: 'red' },
         onMouseDown: [Function],
         onMouseEnter: [Function],
         onMouseOut: [Function],
         onMouseOver: [Function],
         onMouseUp: [Function],
         onMouseLeave: [Function],
         onMouseMove: [Function],
         onClick: [Function],
         onFocus: [Function],
         onBlur: [Function] },
      [Symbol(SameObject caches)]:
       [Object: null prototype] {
         attributes:
          NamedNodeMap {
            '0': Attr {},
            '1': Attr {},
            '2': Attr {},
            '3': Attr {},
            '4': Attr {},
            '5': Attr {} },
         childNodes: NodeList {},
         style:
          CSSStyleDeclaration {
            '0': 'fill',
            _values: [Object],
            _importants: [Object],
            _length: 1,
            _onChange: [Function] } } }

Done in 10.07s.
```

**Comment by cmdcolin** [comment]
In a real *coup de grace*, the flaky test mentioned above passes fine without a timeout in react 16.9 alpha e.g. the #307 branch merged into this one

**Comment by cmdcolin** [comment]
forgive my possibly incorrect usage of the term...but it did end the suffering

**Comment by cmdcolin** [comment]
Prev comment about upgrading to react 16.9 fixing flaky test were not correct, still needs timeout..

**Pull request merged**
