### PR TITLE
New SVG gene glyph with directional arrows

### PR DESCRIPTION
**Pull request by cmdcolin**
This removes the chevron code for directional indications (xref #1909) 

The arrows are added on top level features (e.g. the subfeature Box glyphs do not draw the arrowheads) and it determines this using a topLevel prop

Fun technical detail but this also uses a line+polygon elements instead of a single `polyline` to draw the polygon. Also note there is code drawing arrows like this on main, but it is hidden behind the chevron. 

Reason for polygon+line is because it is sharper this way, see screenshots

polygon triangle
Screenshot from 2022-02-27 19-07-00

polyline triangle, has a little "foot" on the arrow when the polyline presumably doesn't come to a perfect point
Screenshot from 2022-02-27 19-07-14

also converted the svg features to typescript in the process. can separate into multiple PR if helpful

also uses an outline config variable for boxes, instead of only displaying the outline when selected (current main does this) and not use color2 but instead a new config variable that is nothing by default (color2 is the intron color) (xref #2449)

### CODE REVIEW

**Comment by cmdcolin** [comment]
I think the agreement from the meeting was this PR should be ok to go, at least conceptually. any concerns?

one note was that the Chevron glyph is being removed, and we wondered if any third party libs directly used this glyph cc @bbimber

**Comment by bbimber** [comment]
@hextraza Sebastian, could you give this a quick look? I dont think we need chevron; however, we might need to do some tweaks on our plugin to adapt to this.

**Comment by cmdcolin** [comment]
I don't believe chevron is re-exported so should not cause breakage in third party code

**Comment by cmdcolin** [comment]
maybe can merge optimistically :)

**Pull request merged**
