### PR TITLE
Add ctrl+zoom for speedily navigating zoom levels

### PR DESCRIPTION
**Pull request by cmdcolin**
This is an initial result in trying to add zooming with the mouse wheel while holding the ctrl key

I think having this hidden behind the ctrl key modifier keeps vertical scrolling feeling normal, although that does reduce discoverability

Nevertheless, hopefully this could be useful to power users? Feedback welcome

#990

### CODE REVIEW

**Comment by garrettjstevens** [comment]
I like this idea, I think it's a good way to navigate. I think it would be nice to be able to center the zoom at the mouse position, but that could be something to add later.

ctrl+scroll is Chrome's built-in shortcut for changing the browser page zoom level, but since this only affects the view and the browser shortcut still works in other places on the page, I don't think we'll run into any accessibility issues.

One thing I noticed when I tried this out, if I ctrl+scroll my mouse wheel continuously, the animation kind of jumps around and doesn't actually zoom until I stop scrolling.

**Comment by cmdcolin** [comment]
>One thing I noticed when I tried this out, if I ctrl+scroll my mouse wheel continuously, the animation kind of jumps around and doesn't actually zoom until I stop scrolling.

Yep this is the current state of it right now. Didn't investigate whether it could be more continuous

**Comment by rbuels** [comment]
Yeah this is a great starting point to refine it further, I agree the zoom should be centered on the mouse position, and the animation still feels jerky.

**Comment by cmdcolin** [comment]
I made a little effort to make the ctrl+zooming start as soon as you start doing it.

The idea of it being centered on the mouse position is not really considered at the moment, but I think the usability is improved now and starts zooming (using scrollFactor) right when you start doing wheel

**Comment by garrettjstevens** [comment]
I think having it zoom as soon as you start scrolling makes it feel a lot nicer :thumbsup:

**Comment by rbuels** [comment]
This is great, let's see if we can get it to change its zoom point to be the mouse cursor now. Meaning: the display shouldn't *appear* to scroll, but the center of the zooming should be wherever the mouse cursor is.

**Comment by cmdcolin** [comment]
It is likely going to be disorienting unless the scalefactor can center the zoom where you are pointing

**Comment by cmdcolin** [comment]
The way I think it could be hacked in but adds disorientation:

Use just scaleFactor while zoom scrolling
But then when performing the model actions to update zoom, do a model.horizontalScroll first to center view on where to zoom out, then zoom out.

I don't think this is good though, due to the disorientation

The way it is now, it just zooms out from the center, which feels ok



Examples of an app that does real mouse-follow-zoom
https://genomespy.app/examples/TCGA/BRCA/
google maps also does it, etc.

**Comment by cmdcolin** [comment]
Adding it in properly would need to properly follow the mousepointer throughout the zoom I think

**Comment by rbuels** [comment]
we can leave it centered for now, why don't we do real mouse-follow-zoom later. I think it's definitely worth doing, but it can wait if it's hard.

**Comment by cmdcolin** [comment]
Sounds good :)

**Pull request merged**
