### PR TITLE
Add button to bookmark in jbrowse-web share dialog

### PR DESCRIPTION
**Pull request by cmdcolin**
This adds a link to the "ShareDialog" that suggests to right-click to bookmark. This is useful because it can otherwise be hard to generate a bookmark from link in the text field

### CODE REVIEW

**Comment by carolinebridge-oicr** [comment]
While "right click to bookmark" is a thing on Firefox, I don't get the same prompt on Chrome...for a Chrome user this might be confusing?

**Comment by cmdcolin** [comment]
thanks for pointing this out, was hoping chrome would have a similar feature. looks like you can "drag the link to the bookmark bar" in chrome. could use the text "Link for bookmarking" as an alternative.

there is also a method from the igv.js webapp here where you click and then it says to press ctrl+d

image

**Comment by cmdcolin** [comment]
changed the link text to "Link for bookmarking"

**Comment by carolinebridge-oicr** [comment]
I still think it's a little confusing -- I feel like an individual might navigate to the link and then try to bookmark that, without understanding how the share link works.

I looked at it briefly and didn't find anything easy/possible, but a button that does the ctrl+D action on the share link would be perfect...

In lieu of that, maybe have an "info" tooltip that describes copying the link and manually creating a bookmark. It's really annoying (and weird) that Chrome doesn't have a clean equivalent to this.

Also want to point out that single clicking on the text box + right clicking the link we have in there already lets you "bookmark link" on firefox.

**Comment by cmdcolin** [comment]
I changed the action to try out the "Click to bookmark" and then it updates the text to say "Now hit Ctrl/Cmd+D". I feel like it's a bit awkward and crowded, and the two stage process is a bit hard to explain. I do think this feature is valuable, but, not sure how to best present it. It could be a separate action from the share dialog potentially

**Comment by cmdcolin** [comment]
New design 

image


It pops up an alert box after clicking "bookmark" instructing the user to hit ctrl+d/cmd+d

**Pull request merged**
