### PR TITLE
Create in app graphical plugin store

### LINKED ISSUE #336: plugin browser
Make a GUI plugin browser that can 
* fetch a json resource that lists available plugins
* fetch and install a plugin 
* uninstall current plugins

### LINKED ISSUE #1686: session plugins
ability for non-admin users to load plugins in their own sessions, and in sharable sessions.

This obviously brings up security concerns, the draft plan for that would be to allow only plugins that are in the central plugin store to be loaded in sessions.

### PR DESCRIPTION
**Pull request by elliothershberg**
This is currently a draft PR while I get a few things figured out, but works for web. Opening this so I have a better view of the diff on this branch and the state of the CI.

Remaining work:

- [x] Get things working in desktop
- [x] Write tests 😅 
- [x] Merge main and resolve conflicts

This closes #336 and also closes #1686 .

**Screenshots:**

Screen Shot 2021-05-11 at 3 49 08 PM

With MsaView open:

Screen Shot 2021-05-11 at 3 59 55 PM

### CODE REVIEW

**Comment by cmdcolin** [comment]
random note but we could, once we do something like this PR, avoid popping up warning dialogs for external configs on other domains. this is helpful for example in our plugins where we demonstrate them by linking them link `https://s3.amazonaws.com/jbrowse.org/code/jb2/main/index.html?config=<cross domain here>` 

probably the warning popup could be avoided if the plugin is whitelisted aka found in the plugins.json

**Comment by elliothershberg** [comment]
Yeah, I think that would be good to do

**Comment by rbuels** [comment]
this looks great!  few little nits to pick:
* can we get some screen shots in here? This feature will be released with some fanfare, and we will want some nice screen shots
* can we make this widget lazy-loaded? this will probably be used relatively infrequently by end users

**Comment by elliothershberg** [comment]
> I say merge once the above is done

On it!

**Pull request merged**
