### PR TITLE
reorganize the demo page to emphasize the cancer sv demo more

### PR DESCRIPTION
**Pull request by rbuels**
The cancer demo that takes people through the SV features gives grant reviewers a good overview of things without them having to do the work to click around, which I think is important right now.

### CODE REVIEW

**Comment by cmdcolin** [comment]
the page contains broken links, see https://s3.amazonaws.com/jbrowse.org/code/jb2/1322_cancer_genome_demo/?config=test_data%2Fconfig_cancer.json&session=share-kxgcLjxfgE&password=l7tXf it is access denied

**Comment by cmdcolin** [comment]
Another good addition to cancer demo need to update this page and find a convincing breakpoint split view, because the one displayed has not much read evidence, and if possible, one that supports a gene fusion (with additional gene fusion RNA-seq type evidence displayed)

**Comment by rbuels** [comment]
this PR doesn't change any of the links. is s3 being bad again?

**Comment by cmdcolin** [comment]
I don't believe this PR or anything did it, I think the demo just has gotten stale and contains some broken links

**Pull request merged**
