### PR TITLE
Add v2.0.0 release announcement

### PR DESCRIPTION
**Pull request by cmdcolin**
```
## Unreleased (2022-07-05)

#### :rocket: Enhancement
* Other
  * [#3001](https://github.com/GMOD/jbrowse-components/pull/3001) Draw SNPs in modifications/methylation views ([@cmdcolin](https://github.com/cmdcolin))
  * [#3068](https://github.com/GMOD/jbrowse-components/pull/3068) Allow HTML in feature tooltips, remove react-simple-code-editor ([@cmdcolin](https://github.com/cmdcolin))
  * [#3065](https://github.com/GMOD/jbrowse-components/pull/3065) Allow changing between xyplot,line,density for linear wiggle tracks and other small fixes ([@cmdcolin](https://github.com/cmdcolin))
* `text-indexing`
  * [#3058](https://github.com/GMOD/jbrowse-components/pull/3058) Improve bundle size and code splitting on embedded builds (v2) ([@cmdcolin](https://github.com/cmdcolin))
* `__mocks__`, `core`, `text-indexing`
  * [#2949](https://github.com/GMOD/jbrowse-components/pull/2949) Upgrade to MUI v5, mobx-state-tree v5, mobx-react v6, mobx-react v7 ([@cmdcolin](https://github.com/cmdcolin))

#### :bug: Bug Fix
* `core`
  * [#3064](https://github.com/GMOD/jbrowse-components/pull/3064) Fix opening link in new tab by default in feature details ([@cmdcolin](https://github.com/cmdcolin))
  * [#3053](https://github.com/GMOD/jbrowse-components/pull/3053) Avoid displaying [object Object] on deeply nested data in base feature details ([@cmdcolin](https://github.com/cmdcolin))
* Other
  * [#3057](https://github.com/GMOD/jbrowse-components/pull/3057) Fix export SVG crash on some BigWig tracks ([@cmdcolin](https://github.com/cmdcolin))
  * [#3052](https://github.com/GMOD/jbrowse-components/pull/3052) Fix negative value quantitative display in svg exports ([@cmdcolin](https://github.com/cmdcolin))

#### :house: Internal
* [#3067](https://github.com/GMOD/jbrowse-components/pull/3067) Typescriptify some integration tests ([@cmdcolin](https://github.com/cmdcolin))

#### Committers: 2
- Colin Diesh ([@cmdcolin](https://github.com/cmdcolin))
- Garrett Stevens ([@garrettjstevens](https://github.com/garrettjstevens))
Done in 1.80s.


```

### CODE REVIEW

**Comment by cmdcolin** [comment]
after seeing the conflict wiht @scottcain on muiv3 vs v4 in the current gen, it could be considered to be more breaking if embedded users have their site using muiv4 and then we try to upgrade muiv5. we could re-consider this as a major version bump

**Comment by cmdcolin** [comment]
I would like to get this release out sometime soon though, as there are just good general improvements. any thoughts on major version bump?

**Comment by cmdcolin** [comment]
renamed to 2.0.0, will be safer for semver

**Comment by rbuels** [comment]
Hmm let's talk about this tomorrow in grooming

**Pull request merged**
