### PR TITLE
update assemblies to assemblyNames in JB1 text search adapter

### PR DESCRIPTION
**Pull request by teresam856**
Trix adapter was updated here. https://github.com/GMOD/jbrowse-components/pull/2298
Need to update the JB1 text search adapter. AssemblyNames field is used to filter the necessary adapters during a search based on the assemblies those adapters cover.

### CODE REVIEW

**Comment by cmdcolin** [comment]
are there any tests that cover this or a sample config.json file that uses a jb1 text adapter?

**Comment by teresam856** [comment]
We do not currently have tests that use the Jb1 adapter, but we do have Jb1 adapter tests found here plugins/legacy-jbrowse/src/JBrowse1TextSeachAdapter/JBrowse1TextSearchAdapter.test.ts.  It existed at one point, but i think the volvox config was  modified to use a trix adapter instead. Could make a new test for the textSearchManager ?

**Comment by cmdcolin** [comment]
maybe make an alternative volvox_jb1_text_config.json that has the jb1 text index in use. then we can check by hand that it works or, if interested, create an integration test for it

**Comment by cmdcolin** [comment]
lgtm :)

**Pull request merged**
