### PR TITLE
allow manifest to work with authentication

### PR DESCRIPTION
**Pull request by alpapan**
Currently Manifest throws an error when behind authbasic authentication.
This fixes it.

(kudos to https://stackoverflow.com/questions/6294622/html5-manifest-cache-behind-basic-auth)

### CODE REVIEW

**Comment by alpapan** [comment]
addresses https://github.com/GMOD/jbrowse-components/issues/4212#issue-2139822423

**Comment by cmdcolin** [comment]
this is an interesting one. in general, i would be really careful with setting cross origin credentials since it would potentially send credentials to malicious cross origins. it might be ok in this case though since it is hardcoded in the index.

is the manifest important for your use case?

**Comment by alpapan** [comment]
The manifest is not important at all to me!

**Comment by cmdcolin** [comment]
might close this for now, i think it is just best to avoid the security implication if it is generally unused

**Pull request closed without merging**
