### PR TITLE
Add ability to change codon tables for feature sequence panel and sequence track

### PR DESCRIPTION
**Pull request by cmdcolin**
This PR allows you to change codon tables

1) Sequence track
2) Feature sequence calculation (e.g. protein translation of a feature) in the feature detail widget

These are configured basically separately

Different codon tables can be seen here, and is linked from detail dialogs
https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi?chapter=tgencodes#SG2

It currently decides to not have this stored in config, as it is a bit tricky e.g. do we want a translation table per refseq for mitochondrial contig, etc. By making this something a user can select on demand instead of configure by an admin, it puts the responsibility on the user more, but hopefully makes us flexible for diverse use cases

Example screenshots

Feature details settings panel
Screenshot from 2022-05-31 14-11-38

Sequence track codon table panel
Screenshot from 2022-05-31 14-08-41
Screenshot from 2022-05-31 14-08-46

### CODE REVIEW

**Comment by cmdcolin** [comment]
fix aimed at #1765

**Comment by cmdcolin** [comment]
I added a changed concept which makes the concept of the current codon table part of the session.

Before I had it separately set for the reference sequence track, the feature sequence detail panel, and envisioned it would also have to apply to individual feature tracks also once we did #3010...this consolidates it into something that can be changed in a single place on the session. My thought is that someone would likely just be looking at mitochondria by itself if they are concerned with it, and change it then, or something similar

**Comment by cmdcolin** [comment]
this PR might be sufficiently stalled, could maybe close until we get some clarity

**Comment by cmdcolin** [comment]
the non-codon table part of it was migrated to https://github.com/GMOD/jbrowse-components/pull/3216

**Comment by guyleonard** [comment]
I think it's okay to bump this one to ask if there is any current plan to re-implement this feature? (I couldn't find any specifics searching). 

Some of the above talk (and other threads) suggests that the only use case would be for Mitochondria, but we work with Protists (the most diverse group of [microbial] eukaryotes) and many of them have alternative codon usage in their nuclear genomes, e.g. Cilliates where only TGA is used for STOP.

Therefore, it would be really nice for the reference sequence track and also the subfeature detail to allow for different codon uses.

Thanks!

**Comment by cmdcolin** [comment]
thanks for the bump @guyleonard 

this is the currently tracked issue for this https://github.com/GMOD/jbrowse-components/issues/1765

it is a little stalled by trying to decide "how to configure it" (as discussed in the issue, there are some different options like should it be configured per assembly, or should it be per assembly, plus allow certain chromosomes (e.g. chrMT) to get an override, or should users be able to change it in the user interface on the fly as-needed?)

if you have any thoughts on this feel free to detail here https://github.com/GMOD/jbrowse-components/issues/1765

**Pull request closed without merging**
