### PR TITLE
Streamline Gtf

### PR DESCRIPTION
**Pull request by TiaSFlores**
Features added based on reviews and comments. (WIP)

- Adds support for .gtf file format
- Adds directories for each file type

### CODE REVIEW

**Comment by cmdcolin** [comment]
We may want to make meta.json assembly specific unless we amalgamate it all in a single file, but i don't see a benefit to doing that necessarily

**Comment by cmdcolin** [comment]
E.g. volvox_meta.json

**Comment by TiaSFlores** [comment]
Do we need to create a gtf adapter / plugin to use .gtf files in the UI or anywhere else within JBrowse2?

**Comment by TiaSFlores** [comment]
GTF parsing/ formatting is done so what needs to be done next to get it fully implemented?  Currently, trix reads its indexes and searches them fine but we need to plan a gtf adapter still.

**Comment by cmdcolin** [comment]
this PR looked like a great step towards GTF and other types of indexing. maybe we can go ahead with merge :)

**Pull request merged**
