### PR TITLE
Simplify command unzip

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a proposal to use extract-zip to download the jbrowse zip

https://github.com/maxogden/extract-zip/blob/master/index.js

### CODE REVIEW

**Comment by cmdcolin** [comment]
I am not offended if this seems unnecessary.

Also note: I removed logic related to try { ... } catch(e) { this.error(e) } because I think we wouldn't need to manually catch this error, we can rely on https://oclif.io/docs/error_handling

**Comment by cmdcolin** [comment]
Reason for the extract zip instead of unzipper, we had to do things like manually creating directories, etc but I believe unzipping logic is sufficiently complicated, especially if, for example, someone provides a custom zip that could contain symlinks, that we should use extract-zip

**Comment by garrettjstevens** [comment]
I liked that node-unzipper was able to just handle the stream and not have to ever write the intermediate ZIP to disk, but not being able to handle symlinks (which node-unzipper doesn't seem to have any support for) probably makes this change worth it.

**Comment by cmdcolin** [comment]
Looks like this was a botched merge and fails on mac. Reverting probably

**Comment by cmdcolin** [comment]
Something to do with the realpath, symlinks, but kind of unclear

**Comment by garrettjstevens** [comment]
Maybe something to do with os.tmpdir() [not being a real path on Mac](https://github.com/nodejs/node/issues/11422)? We do this as a workaround in the CLI test utils:

https://github.com/GMOD/jbrowse-components/blob/ab4d4664bbafae663500407962d03423e422a0ae/packages/jbrowse-cli/src/testUtil.ts#L10-L11

**Comment by cmdcolin** [comment]
Ya this was something  and we just tried a couple things but this neither this nor wrapping the result of fs.mkdtempSync worked to fix it

**Pull request merged**
