### PR TITLE
this color scheme for ClinVar seems pretty common

### PR DESCRIPTION
**Pull request by scottcain**
I thought this was a nice (minor) addition to the clinvar tracks

### CODE REVIEW

**Comment by cmdcolin** [comment]
looks good :)

image

**Comment by cmdcolin** [comment]
could make into a reusable js function perhaps, but works for now

**Comment by bbimber** [comment]
@scottcain or @cmdcolin: i was looking over the release notes and came across this. A tangential question: this is an example where a non-trivial JEXL expression is duplicated. JEXL does let one define/register custom functions. Have you considered exposing this in some manner to the session, such that a developer could register custom JEXL expressions with the JBrowse JEXL instance once, and then just reference them in the track config?

**Comment by cmdcolin** [comment]
@bbimber not sure if you are using this method or not, but you can use a plugin to register a new jexl function like you refer to https://jbrowse.org/jb2/docs/config_guides/customizing_feature_colors/  you mention exposing it on the session but as the link shows it is exposed on the 'pluginManager'


it would be nice if jexl was a bit more powerful and you could e.g. store the get(feature,'INFO').CLNSIG in a variable in this example, but  making the custom plugin with custom jexl functions is sort of the current workaround

**Comment by cmdcolin** [comment]
also, if you are using the embedded, you do not even need to write a plugin in this case, as you can access the pluginManager with  something like this wherever you want in your code

```typescript
const {pluginManager}=getEnv(session) // or getEnv(viewModel), getEnv(displayModel), etc. getEnv works on any model because every model has the same env with the pluginManager, it is "globally available" via the env
```

**Comment by bbimber** [comment]
@cmdcolin, ok, thanks for the reply. we are doing something similar in our embedded case (which is using plugins for everything). I was musing above about whether sharing of non-trivial JEXL expressions is possible, but it seems like plugin is a reasonably minimal way to do this.

**Comment by cmdcolin** [comment]
oh right. I think I would aim to make non-trivial stuff into js callbacks via the plugin method. this example in this PR would probably benefit from being made into a small callback :) ya, i see you maybe were referring to sharing actual pure jexl expressions across multiple callbacks, but i think just going straight to the custom jexl functions is maybe what i'd do

**Comment by bbimber** [comment]
> oh right. I think I would aim to make non-trivial stuff into js callbacks via the plugin method. this example in this PR would probably benefit from being made into a small callback :) ya, i see you maybe were referring to sharing actual pure jexl expressions across multiple callbacks, but i think just going straight to the custom jexl functions is maybe what i'd do

The impetus for starting this thread was noticing a long JEXL repeated twice in the same JSON config file of this commit, related to color. If the JSON config had some kind of hook to register JEXL (and it seems like registering a custom plugin is the best current option), then that duplication could have been avoided. In theory the JSON config could be extended to more directly let a developer define/register JEXL, but given what's possible I'm not sure that's needed. 

That's all I was asking about, and the answers here have been helpful.

**Comment by scottcain** [comment]
Did I copy and paste code on a quicky change to make my life easier? yes. Should I have? Nope!

**Comment by bbimber** [comment]
> Did I copy and paste code on a quicky change to make my life easier? yes. Should I have? Nope!

not meant as any sort of a critique...just trying to understand capabilities of jbrowse. it's all a balance of time and effort.

**Comment by scottcain** [comment]
I didn't take it as one; I just realize that a config like this is really a teaching tool so I should have thought of that. Do I copy and paste jexl in my own configs: absolutely :-)

**Pull request merged**
