### PR TITLE
Add some features that are missing from jbrowse 2 to the feature comparison table

### PR DESCRIPTION
**Pull request by cmdcolin**
Xref https://github.com/GMOD/jbrowse-components/discussions/1580

### CODE REVIEW

**Comment by rbuels** [comment]
If you put the lack of URL query stuff in, you should add the embedded functionality ;-)

**Comment by cmdcolin** [comment]
What do you mean by "embedded functionality"?

**Comment by cmdcolin** [comment]
You mean the react lgv component?

**Comment by rbuels** [comment]
yes the react component

**Comment by cmdcolin** [comment]
I added a section about embeddability, it is hard to be super concise for it to be simply put in the simple feature comparison so the section helps expand on a couple things.

**Pull request merged**
