### PR TITLE
513 assembly management

### LINKED ISSUE #513: assembly management
GUI functionality to add an assembly, look at the list of assemblies, rename assemblies, look at/change the attributes of the assemblies, and delete assemblies.

assembly CRUD basically.

### PR DESCRIPTION
**Pull request by elliothershberg**
A graphical user interface to create, read, update, and delete assemblies in admin mode. Closes #513

### CODE REVIEW

**Comment by cmdcolin** [comment]
I think that moving config editor to core is maybe would be discouraged compared to implementing this in jbrowse-web


The fact that "we need assembly manager in both desktop and web, so it is therefore core, and then this requires moving config editor and assembly manager UI into core" I think is maybe an anti pattern

instead we can make this code on jbrowse-web, and then think about adding it to jbrowse-desktop later and/or deduplicating into a separate app-core

here is an alt-branch with this change
https://github.com/GMOD/jbrowse-components/compare/513_assembly_management_colin
This alt branch also merged origin/master



PS Fun talk by Dan Abramov on somewhat related topic avoiding too-DRY-code
https://www.deconstructconf.com/2019/dan-abramov-the-wet-codebase

**Comment by garrettjstevens** [comment]
I think this works fine as-is and we can worry about what code belongs in core/app-core etc. as part of #1105.

**Comment by elliothershberg** [comment]
> The fact that "we need assembly manager in both desktop and web, so it is therefore core, and then this requires moving config editor and assembly manager UI into core" I think is maybe an anti pattern

@cmdcolin I can take a look at where you moved things on that branch, but what do you see as the anti-pattern here? @garrettjstevens and I had talked about what else is needed to wrap up this PR, and getting this hooked into the desktop app is one of them, so we would need these components in both places. Moving this code to web wouldn't work for that.

**Comment by cmdcolin** [comment]
Desktop is not needed for this pr I think. Its good to not forget about desktop certainly, but the need to core-ify config editor and assembly manager gui so desktop and web can share is an anti pattern. Instead keep config editor in plugin-config, make assembly manager web only for now (imo)

**Comment by elliothershberg** [comment]
The web app is broken on that branch, so I'm going to wrap up a few things on this branch for now

**Comment by cmdcolin** [comment]
>The web app is broken on that branch

in what way is it broken?

```
git checkout 513_assembly_management_colin
yarn
yarn start
```

starts up ok for me.

I am not gonna push the changes i made too hard here but
a) it involves less code changes on my branch
b) it is up to date with master
c) the idea of just merging this so that we can go back and change it later is not necessarily ideal

**Comment by elliothershberg** [comment]
So I just added a few of my local changes to this branch. One of them is that it now it is on both desktop and web, which is sort of the goal of structuring the code this way, do you still think this isn't right?

If this seems okay, I can get this up to date with master, write tests for AssemblyManager, and should be good to go

**Comment by cmdcolin** [comment]
>do you still think this isn't right?

On some level, yes, I do not really think that adding this to core is correct

I think that if we want to create deduplication within our system, we will want to create a new package called like "app-core" or something. For now, duplicating to code is to me, a better way to go.

**Comment by elliothershberg** [comment]
So you would prefer:

- Move configEditor back to plugin
- Move AssemblyManager to web and desktop
- When we deal with #1105 move this duplication to app-core

Right?

To help me understand, what is the difference between `core/ui` and what will be `app-core`? Why not put the shared UI components in `core/ui`?

**Comment by cmdcolin** [comment]
I tried to outline my views clearly

- See https://github.com/GMOD/jbrowse-components/compare/513_assembly_management_colin for the code. I already moved it back to a plugin. You do not have to do that if you extend that branch or merge it into this one

Also web is being released imminently, desktop is not, that is why I am trying to deflect desktop decision making around this, but if there is strong interest, please see my branch for my proposed code change for web. For desktop it would be similar with duplicating some code to desktop.


> Why not put the shared UI components in core/ui?

They are only shared between "app" level products. Therefore they bloat our concept of core to include things that are intrinsic to our jbrowse-web/jbrowse-desktop concepts. 

Also @rbuels has noted before that core should be somewhat minimal, because it is harder to remove stuff from core than it is to add it BECAUSE it is somewhat like a contract if plugins start depending on it

**Comment by cmdcolin** [comment]
And I do understand we already have App in core, it's already a muddled concept, but this PR extends this and moves even more stuff to core, namely changing stuff that was once a modular package/plugin (config), in order to achieve its goals and I think that is an anti-pattern

**Comment by rbuels** [comment]
Looks like great progress! Having a look at the code, I just have a couple of architectural requests, which I think are in line with what Colin was saying:

* let's put the assembly management GUI either in the existing data-management plugin (packages/data-management), or make another plugin for it
* let's leave the config editing code where it is

Just pair with me, Colin, or Garrett and we'll put our heads together on how to accomplish this.

**Comment by garrettjstevens** [comment]
@rbuels I'm not sure assembly management belongs in a plugin. I think it fits more into shared app-core code.

**Comment by rbuels** [comment]
superseded by #1349

**Pull request closed without merging**
