### PR TITLE
Config file import UI

### LINKED ISSUE #152: load a configuration JSON from the top menu bar

### LINKED ISSUE #247: Use generic-filehandle for LocalFile and BlobFile
We should integrate @cmdcolin's `generic-filehandle`. Using `generic-filehandle` actually already works if you do this:

```diff
diff --git a/packages/jbrowse-web/src/util/io/index.js b/packages/jbrowse-web/src/util/io/index.js
index 7195301..e2e120f 100644
--- a/packages/jbrowse-web/src/util/io/index.js
+++ b/packages/jbrowse-web/src/util/io/index.js
@@ -1,10 +1,9 @@
-import { openUrl } from './rangeFetcher'
-import LocalFile from './localFile'
+import { LocalFile, RemoteFile } from 'generic-filehandle'
 
 // eslint-disable-next-line import/prefer-default-export
 export function openLocation(location) {
   if (!location) throw new Error(`must provide a location to openLocation`)
-  if (location.uri) return openUrl(location.uri)
+  if (location.uri) return new RemoteFile(location.uri)
   if (location.localPath) {
     return new LocalFile(location.localPath)
   }
```
which is pretty cool. We'll want to not use RemoteFile for now, though, until we can integrate it with `http-range-fetcher`.

Need to add BlobFile to `generic-filehandle` first (see https://github.com/cmdcolin/generic-filehandle/issues/1).

### PR DESCRIPTION
**Pull request by garrettjstevens**
Not quite ready yet, but wanted to start a discussion about how to handle config imports. I'll explain more in comments below.

Quick preview of what it's looking like:
image

resolves #152
resolves #247

### CODE REVIEW

**Comment by garrettjstevens** [comment]
When importing a config file, is there anything about the user's current session that needs to be kept? (By "session" I mean anything in the rootModel except for the configuration section)

To me it doesn't make sense to keep anything, since the views, tracks, etc. are all dependent on a specific config, so importing a new config is basically going to create a new session. I want to make sure I'm not missing something, though.

**Comment by rbuels** [comment]
i can't think right now of anything that needs to be kept

**Comment by garrettjstevens** [comment]
I think this is ready for review. To test:
* grab your favorite config file
* remove or change the "sessionName" entry under "defaultSession" (or remove "defaultSession" altogether)
* click "Import configuration" under the "Admin" menu bar entry
* Hopefully the rest is self-explanatory

**Comment by garrettjstevens** [comment]
As discussed in the meeting, this needs:
* Filesize limit
* A way of getting rid of files in the list (so you can remove one with error, reset the UI, etc.)

**Pull request merged**
