### PR TITLE
Creates gtf plugin

### PR DESCRIPTION
**Pull request by teresam856**
* Old PR #2212 

This is a new updated PR, attempts to replace #2212
[Issue 1889, tabix-indexed GTF data adapter](https://github.com/GMOD/jbrowse-components/issues/1889)
In this PR:
* creates gtf parser now found [here](https://github.com/GMOD/gtf-js), and published [here](https://www.npmjs.com/package/@gmod/gtf)
* creates a gtf plugin with a gtf tabix adapter and [plain text gtf adapter](https://github.com/GMOD/jbrowse-components/issues/2365)
* creates test for gtf tabix adapter
* creates test for gtf adapter
* adds gtf plugin to core plugins in desktop and in web
* tested with human (GRCh38) data
*  fix rendering of features in gtf adapter

Jb1 gtf track
jb1_gtf_track

jb2 gtf track
jb2_gtf

### CODE REVIEW

**Comment by rbuels** [comment]
any reason this is still draft?

**Comment by teresam856** [comment]
> any reason this is still draft?

Just fixing an error with a dependency. Other than that it should be ready for review.

**Comment by cmdcolin** [comment]
can we add a plaintext gtf adapter for this also?

**Comment by teresam856** [comment]
> can we add a plaintext gtf adapter for this also?

yeah we can add it!

**Comment by teresam856** [comment]
converting to draft again to add plaintext gtf adapter

**Comment by teresam856** [comment]
Screen Shot 2021-11-01 at 4 43 47 PM


plain text and tabix gtf example tracks

**Comment by cmdcolin** [comment]
excellent :)...maybe we can add the gtf tabix and plaintext gtf to the volvox config.json?

**Comment by teresam856** [comment]
> excellent :)...maybe we can add the gtf tabix and plaintext gtf to the volvox config.json?

you got it! 👍

**Comment by teresam856** [comment]
unrelated to this pr: there may be an issue/bug with the text index command that could be causing the failure when adding the gtf tracks

**Comment by cmdcolin** [comment]
there is vestigial gtf indexing code in text-index that may want to be removed or fixed up. unless it seems easy to hook up, can probably opt for removal for now

**Comment by cmdcolin** [comment]
this looks like there are some bugs where incomplete features are buffered in

this may be due to redispatching not working or other problems with the parser

see here: screenshot where the GTF features are starting inside the viewed window (incorrect position) while the GFF3 tabix features go off the screen to the left

localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-F3sahczVq

**Comment by cmdcolin** [comment]
actually, tabix GTF will not work, pretty much full-stop, because there is no parent feature that can be used for redispatching. therefore, we can realistically only support plaintext GTF

**Comment by cmdcolin** [comment]
see example file


```
ctgA	example	exon	1050	1500	.	+	.	transcript_id "EDEN.1"; gene_id "EDEN"; gene_name "EDEN";
ctgA	example	exon	1050	1500	.	+	.	transcript_id "EDEN.2"; gene_id "EDEN"; gene_name "EDEN";
ctgA	example	five_prime_UTR	1050	1200	.	+	0	transcript_id "EDEN.1"; gene_id "EDEN"; gene_name "EDEN";
ctgA	example	five_prime_UTR	1050	1200	.	+	0	transcript_id "EDEN.2"; gene_id "EDEN"; gene_name "EDEN";
ctgA	example	CDS	1201	1500	.	+	0	transcript_id "EDEN.1"; gene_id "EDEN"; gene_name "EDEN";
ctgA	example	CDS	1201	1500	.	+	0	transcript_id "EDEN.2"; gene_id "EDEN"; gene_name "EDEN";
ctgA	example	exon	1300	1500	.	+	.	transcript_id "EDEN.3"; gene_id "EDEN"; gene_name "EDEN";
ctgA	example	five_prime_UTR	1300	1500	.	+	1	transcript_id "EDEN.3"; gene_id "EDEN"; gene_name "EDEN";

```

in a GFF3 file, we would have a parent "gene" feature that encloses all the child features. if we are zoomed in, we'd detect that a parent feature exists, expand our query range to get all the child features, and redispatch. can't be done with gtf though

**Comment by cmdcolin** [comment]
due to reasons similar to the no-redispatching, performing text indexing on the plaintext gtf is also hobbled if doing the line-by-line, since line-by-line info is not really sufficient to make a good feature index entry, so GtfAdapter feature indexing is disabled

**Pull request merged**
