### PR TITLE
Fix LGV navigation after a display region change

### PR DESCRIPTION
**Pull request by cmdcolin**
Possible fix for #1702

### CODE REVIEW

**Comment by cmdcolin** [comment]
@teresam856 can you check? the bug #1702 tracking this showed via git bisect that this may have been traced to commit 491a1e58

**Comment by teresam856** [comment]
> @teresam856 can you check? the bug #1702 tracking this showed via git bisect that this may have been traced to commit [491a1e5](https://github.com/GMOD/jbrowse-components/commit/491a1e58ac1edaa8e4391084f3ff9eb89892d033)

Yeah I can check. What are the steps to replicate the bug?

**Comment by cmdcolin** [comment]
1. Show all regions in assembly
2. Then use refnameautocomplete to nav to chr1

The scroll position is weird after doing that

**Comment by cmdcolin** [comment]
This PR should fix that, however I wanted to make sure it didn't have conflict with work that you had done since it was introduced in the PR that https://github.com/GMOD/jbrowse-components/commit/491a1e58ac1edaa8e4391084f3ff9eb89892d033 was in

**Comment by teresam856** [comment]
> This PR should fix that, however I wanted to make sure it didn't have conflict with work that you had done since it was introduced in the PR that [491a1e5](https://github.com/GMOD/jbrowse-components/commit/491a1e58ac1edaa8e4391084f3ff9eb89892d033) was in

Hmm that is interesting. I had not seen weird scrolls. No it should not conflict. In that commit, I deleted model.showAllRegions() when merging the functionality of the header and import form to have them both do the same thing as in the [import form](https://github.com/GMOD/jbrowse-components/blob/master/plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx#L61-L73)

**Comment by teresam856** [comment]
I think the fix should be ok. It should not interfere with that commit.

**Review by teresam856 — APPROVED** [review]
lgtm

**Comment by cmdcolin** [comment]
@teresam856 thanks for the details

This is good info to note actually, because we could add model.showAllRegions to ImportForm also,


This will actually markedly change the users experience with the browser, because then by default, when they enter chr1, then will enter it as the entirety of chr1 rather than chr1:1-1000 which is basically what we do now

It may be that this is a better behavior actually

**Comment by cmdcolin** [comment]
I will merge this PR because it is important to get in but make a new issue with discussion about it

**Pull request merged**
