### PR TITLE
Autodeploy website

### PR DESCRIPTION
**Pull request by cmdcolin**
This autodeploys the website with a github workflow when a commit uses the phrase "update docs"

Could also just be "^docs" if we use conventional commits

### CODE REVIEW

**Comment by cmdcolin** [comment]
Note that this already did a run thru and appeared to work ^_^

Does the pdf and the docusaurus website

**Comment by rbuels** [comment]
wow this is cool!

**Comment by cmdcolin** [comment]
yaw. should be good to go now. there wasn't a way to have "pandoc in the path" it needs to specifically call the "pandoc docker container" hence some rejuggling of stuff but its not too bad

**Comment by cmdcolin** [comment]
made it only run on master in case maybe an arbitrary drive-by PR by evildude could make the website update

**Pull request merged**
