### PR TITLE
Add removable-media to jbrowse desktop snap

### PR DESCRIPTION
**Pull request by cmdcolin**
May help with https://github.com/GMOD/jbrowse-components/issues/3683

I am unable to build the electron-builder binaries locally (could be a separate issue, it is just confusing for my build environment) so difficult to test this

### CODE REVIEW

**Comment by vvmorita** [comment]
Thank you so much for your attempt. However, I encountered another issue while trying to build the snap (v2.6.1). I received the following error messages:
error: cannot read snap file: cannot have plug and slot with the same name:
       "removable-media"
Perhaps it would be better to revert back to the previous version (v2.5.0).

**Comment by cmdcolin** [comment]
@vvmorita thanks for letting me know. I now just for the first time even tested trying to install the snap locally with e.g. `sudo snap install --dangerous jbrowse-desktop-v2.5.0-linux.snap` on ubuntu and v2.5.0 does indeed work but v2.6.1 has the error. I can try one more thing with the removable-media thing in next release

**Comment by cmdcolin** [comment]
@vvmorita new version v2.6.2 released with the bug somewhat reverted. not sure if it helped, but can be installed now at least!

**Comment by vvmorita** [comment]
Thank you for letting me know. The new snap version couldn't access
removable media, but somehow the AppImage version worked perfectly this
time. Overall, things are going well. Many thanks.

2023年7月13日(木) 23:52 Colin Diesh ***@***.***>:

**Pull request merged**
