### PR TITLE
Provide genomic context for linear vs. ref

### PR DESCRIPTION
**Pull request by elliothershberg**
This PR proposes to expand the start and end of the reference linear view when opening a linear vs. ref view. I think that this helps avoid cutting off details on the reference genome surrounding the read.

Example:

image

The current solution is add a region that is the length of the read to the left and right side of the read for the reference.

i.e.

image

This was motivated by #1322

### CODE REVIEW

**Comment by cmdcolin** [comment]
On some level, I like the precision of the current solution, because it matches everything up perfectly. I might prefer if it were an option to add extra space

**Comment by cmdcolin** [comment]
To me, the breakpoint split view itself could use something helpful that provides genomic context of more side by side of a breakpoint, but the read vs ref is based on a continuous alignment of the read versus the reference?

**Comment by cmdcolin** [comment]
This is something I have tried to propose a bunch of times with #655 and is probably not that technically difficult to set up, but would be pretty valuable

**Comment by elliothershberg** [comment]
@cmdcolin all good points. Do you have any thoughts for a straightforward way to implement this type of zooming out being optional? One way could be to create the reference view with the proposed new start and end, but (if possible) start zoomed in to the previous view. I think it would really help this view to not be cut off to seeing some surrounding parts of the region.

Re #655 , sounds cool. Would be neat to be able to toggle back and forth between side by side and stacked.

**Comment by rbuels** [comment]
I'm a little confused ... could somebody paste before and after screenshots of what this change looks like?

**Comment by cmdcolin** [comment]
Here is an example from our docs

Before


After
localhost_3000__config=test_data_config_demo json (4)


This is an interesting one because, while I don't like how it visually looks afterwards, it is a good example because after Elliot's change, it shows that the read is aligning to basically regions of copies of the same gene (WASH* in all three panels), which was not as obvious in the panel without the context.

**Comment by cmdcolin** [comment]
Maybe using the word "don't like how it looks afterwards is too strong" but it is "less continuous of an alignment"

**Comment by cmdcolin** [comment]
By creating this example, it does suggest that adding this change could be useful. Possibly with a popup box that let's you configure the window size?

**Comment by elliothershberg** [comment]
Nice, thanks @cmdcolin for adding the screenshots. It's funny, I personally like the way it looks visually a bit more!

So what is your thought on workflow:

click linear vs. ref --> popup for determining window size --> view opens?

I do like the way it automatically opens right now, but could do a branch w/ this to see

**Comment by rbuels** [comment]
what if the borders of the displayed regions were draggable, so people could expand them a little to see more context if they want?

**Comment by cmdcolin** [comment]
Added a dialog helper

localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-jANtoczft

**Comment by cmdcolin** [comment]
Regarding the suggestion of directly dragging displayed region borders, I think it might be difficult and a bit niche. I think the dialog pretty well solves it :)

**Pull request merged**
