### PR TITLE
Create "quickstart list" on jbrowse-desktop which users can add to

### PR DESCRIPTION
**Pull request by cmdcolin**
Concepts

1) Downloads https://jbrowse.org/genomes/sessions.json at electron app startup, using code in electron.ts
2) Splits the sessions.json file (containing multiple assemblies, etc) into separate files in ~/.config/@jbrowse/desktop/quickstarts/hg19.json, hg38.json, etc.
3) Users can add their own files to the quickstart list by using a star icon on the recent session panel
4) Users can delete and rename quickstarts
5) Deleted quickstarts get a '.deleted' file added e.g. hg19.json.deleted which means, they can delete things that would come from the sessions.json
6) The quickstart list is updated in the GUI every 500ms. This is easier and maybe even better than designing an observable/reactive system because it is hard to design a reactive system based on the filesystem, and often polling is the best way here (even typescript does polling on a large scale).

Screenshot
Screenshot from 2021-10-07 12-53-53

### CODE REVIEW

**Comment by garrettjstevens** [comment]
I worry that the star icon might be confusing, since users might expect it to act like a bookmark or a favorite within that list, instead of it getting copied to a different list. What if adding to the quickstart list was a bulk action like delete?

**Comment by garrettjstevens** [comment]
Not sure about any of the built-in icons, but we could do a custom one like in `packages/core/ui/Icons.tsx`. I like "file-move" from https://materialdesignicons.com/:

materialdesignicons com_

```jsx
function FileMove(props: SvgIconProps) {
  return (
    <SvgIcon {...props}>
      <path d="M14,17H18V14L23,18.5L18,23V20H14V17M13,9H18.5L13,3.5V9M6,2H14L20,8V12.34C19.37,12.12 18.7,12 18,12A6,6 0 0,0 12,18C12,19.54 12.58,20.94 13.53,22H6C4.89,22 4,21.1 4,20V4A2,2 0 0,1 6,2Z" />
    </SvgIcon>
  )
}
```

**Comment by garrettjstevens** [comment]
Would that be confusing to iOS users who might think it means share session? I don't use iOS so I'm not a good judge.

**Comment by cmdcolin** [comment]
if there is worry about overlap there, could go into the "bookmark" realm of icons, and be pretty vague still here too

Screenshot from 2021-10-11 17-40-44


or
Screenshot from 2021-10-11 17-41-38

**Pull request merged**
