### PR TITLE
Bigbed adapter

### PR DESCRIPTION
**Pull request by rbuels**

### CODE REVIEW

**Comment by cmdcolin** [comment]
I rebased this off master and added some parsing using the @gmod/bed module. This module might need to solve the unique id generation problem, possibly upstream in @gmod/bbi

localhost_3000_ (11)

**Comment by cmdcolin** [comment]
I'll look into the unique ID generation, it looks like there may have been a method based on file offsets in jb1

**Comment by cmdcolin** [comment]
The uniqueId issue is resolved now with integration of @gmod/bed@2.0.0

**Comment by rbuels** [comment]
🚀 🔥

**Comment by rbuels** [comment]
just need to add `getFeatureStream` usage to this, then i think it's good to merge

**Pull request merged**
