### PR TITLE
1674 open track bug

### PR DESCRIPTION
**Pull request by teresam856**
Proposal to fix bug [1674](https://github.com/GMOD/jbrowse-components/issues/1674)
Jbrowse web currently crashes when we click File -> Open Track while an import form is being rendered due to 

This PR
- Removes retrieving assemblyName from displayedRegions in the addTrackWidget model.ts. Not all views have displayedRegions @ session.views[0] (e.g synteny which has them @ session.views[0].views) which causes 'TypeError: Cannot read property 'assemblyName' of undefined'. DisplayedRegions can also be undefined when opening a view (import form) but displayedRegions are still yet to be defined which will throw the same error. 

- Small test in CircularView. Tests being able to click `Open Track` from circular view set up wizard without crashing Jbrowse web.

Can remove utilizing the  `self.view.displayedRegions[0].assemblyName` in the addTrackWidget `get assembly()` or maybe add more options for retrieving the assemblyName.

### CODE REVIEW

**Comment by cmdcolin** [comment]
@teresam856 what about just this as the change?


```
diff --git a/plugins/data-management/src/AddTrackWidget/model.ts b/plugins/data-managem>
index c03b7071c..c27a017b8 100644
--- a/plugins/data-management/src/AddTrackWidget/model.ts
+++ b/plugins/data-management/src/AddTrackWidget/model.ts
@@ -108,7 +108,7 @@ export default function f(pluginManager: PluginManager) {

       get assembly() {
         return (
-          self.altAssemblyName || self.view.displayedRegions[0].assemblyName
+          self.altAssemblyName || self.view.displayedRegions[0]?.assemblyName
         )
       },

```

**Comment by teresam856** [comment]
> @teresam856 what about just this as the change?
> 
> ```
> diff --git a/plugins/data-management/src/AddTrackWidget/model.ts b/plugins/data-managem>
> index c03b7071c..c27a017b8 100644
> --- a/plugins/data-management/src/AddTrackWidget/model.ts
> +++ b/plugins/data-management/src/AddTrackWidget/model.ts
> @@ -108,7 +108,7 @@ export default function f(pluginManager: PluginManager) {
> 
>        get assembly() {
>          return (
> -          self.altAssemblyName || self.view.displayedRegions[0].assemblyName
> +          self.altAssemblyName || self.view.displayedRegions[0]?.assemblyName
>          )
>        },
> ```

I had actually just put this [change in pr 1679](https://github.com/GMOD/jbrowse-components/pull/1679/files) before you commented here. I wanted to also check if self.view.displayedRegions exist because synteny does not have displayedRegions in self.view
Screen Shot 2021-02-09 at 11 46 46 AM

**Comment by cmdcolin** [comment]
Ah nice...I think that looks like the better fix

**Comment by teresam856** [comment]
> Ah nice...I think that looks like the better fix

I will close the other proposal.

**Pull request closed without merging**
