### PR TITLE
Improve mobx-state-tree type validation errors

### LINKED ISSUE #1515: Mis-spelled type results in infinite loop
Steps

- Rename BamAdapter to BadAdapter in a config.json
- Load config.json
- Observe that it infinite loops the browser basically

### PR DESCRIPTION
**Pull request by cmdcolin**
This is an attempt to improve the loader error

Fixes #1515 

Note that this issue of the infinite CPU only happens due to react-error-overlay in dev but is now fixed by this and attempts to additionally improve the situation by providing a slightly more readable abbreviated error message than the default

Screenshot

localhost_3000__config=test_data_volvox_config json (1)

This helps us understand potentially the track the failed to load, and the "path" e.g. it is the first track

### CODE REVIEW

**Comment by cmdcolin** [comment]
Also note, we had built in a workaround for this 100% CPU error before but it was lost during the loader refactoring

**Comment by cmdcolin** [comment]
requires a special config to get the proper error messages in production

xref https://github.com/mobxjs/mobx-state-tree/issues/1469

**Comment by cmdcolin** [comment]
added to jbrowse-desktop also to try to prevent desktop from getting out of sync

manually created a factory reset button for it

Screenshot from 2020-12-20 14-48-11

**Comment by cmdcolin** [comment]
any thoughts on this one? I think the error message simplicity is 10x better with this change. This does make it so that we have type checking in production, which could incur some performance hits in some places, I'm not really sure where, but is needed to get the proper error message in production (it will still fail if we have something like BadAdapter in production but the message is less informative, yet still really long....this change makes it so even in production we can probably get a short nice message)

Probably also would fix #756

**Review by garrettjstevens — APPROVED** [review]

**Comment by cmdcolin** [comment]
We got a thumbs up :) maybe we go ahead and merge...can revisit if needed

**Pull request merged**
