### PR TITLE
typescripting more of core, subadapter and sequence adapter instantiation

### PR DESCRIPTION
**Pull request by rbuels**
This adds a test for what I think @cmdcolin was talking about in #797, but the test just passes.

@cmdcolin do you think you could expand on this test to make it fail and illustrate the behavior you are talking about in #797?

### CODE REVIEW

**Comment by cmdcolin** [comment]
The problem is getConf(track, 'adapter') or something with subparts

The adapter does not actually receive a conf object but a json-ified thing that comes over the RPC

So it receives getConf(track, 'adapter') which makes it fail

I added a test that makes it fail in a similar way, it just tries to get the value of a nested config, even though this is not what actually happens in the code

**Comment by rbuels** [comment]
If it's an instantiated config object, you can readConfObject or getConf with an array of slot names to fetch things in subschemas, is that what you're looking for? Maybe I'm still not quite getting it.

**Comment by cmdcolin** [comment]
There is code that literally calls getConf(track, 'adapter') in the code in order to pass the adapter config to the backend. Any defaultValue things that are inside the adapter config are not passed to the adapter via the RPC due to this.

**Comment by cmdcolin** [comment]
You can duplicate some of the logic in order to get the defaultValue that you expect but this is sort of undesirable

```
class MyAdapter {
constructor(args) {
   if(args.dontRedispatch===undefined) {
       args.dontRedispatch='the value that I know is the defaultValue in my configSchema'
   }
}
}
```

**Comment by rbuels** [comment]
OK I think I'm finally getting it. The schema should be re-inflated on the other side of the RPC boundary, instead of using the config snapshot directly. let me look at where the best place to do that is.

**Comment by rbuels** [comment]
Yeah I think the best thing is to leave it up to each adapter to inflate the config snapshot, or not, as it sees fit. So in the case of the GFF3Tabix adapter, it should probably just do something like `const myconf = configSchema.create(adapterConfig)` inside its constructor, then use readConfObject or whatnot so that the defaults are populated. What do you think about that @cmdcolin?

**Comment by cmdcolin** [comment]
Seems alright, I can get that to work. I think perhaps this should be propagated across adapters just as general practice

**Comment by rbuels** [comment]
i'm going to close this PR and make a new one that better captures what this work is turning into

**Pull request closed without merging**
