### PR TITLE
Remove function strings and eval usage

### LINKED ISSUE #1841: Remove eval from jbrowse1connection
Currently jbrowse1connection maintains usage of eval

Since we have sessionConnections, there can be an xss risk

### PR DESCRIPTION
**Pull request by cmdcolin**
Fixes #1841

### CODE REVIEW

**Comment by cmdcolin** [comment]
This of course loses some  jbowse 1 compatibility, but it could be considered as needed still

**Review by garrettjstevens — APPROVED** [review]

**Comment by rbuels** [comment]
we don't want to remove these yet, we will need to use them for allowing admins to add functions

**Comment by cmdcolin** [comment]
Admins will add custom jexl functions no?

**Comment by rbuels** [comment]
no, custom JS functions. cause you can't do everything with jexl.

**Comment by rbuels** [comment]
the custom JS functions would be called from jexl

**Comment by cmdcolin** [comment]
if an admin can create jexl addFunction commands in a plugin, that could be an alternative

we don't have any concept of even interpreting plain function strings as far as I can tell right now

**Comment by rbuels** [comment]
The JB1 callback compatibility is a security risk of XSS injection via connecting to a malicious JB1, but perhaps we can mitigate it without removing callback compatibility entirely?

**Comment by rbuels** [comment]
maybe by popping up a dire warning when connecting to a JB1 that has callbacks

**Comment by cmdcolin** [comment]
Relying on dire warnings for security seems like an anti-pattern that would be best to get rid of, and just bite the bullet with this one as jb1 backcompat will never be first class

**Comment by rbuels** [comment]
@garrettjstevens do you think having "pretty good" back compat for JB1 callbacks is realistically achievable for us? If the answer is "not really", then removing this stuff would make sense

**Comment by garrettjstevens** [comment]
I would have to say the answer is "not really". I think there's just too much variability in the callbacks to realistically get a good return on our time trying to handle them.

**Comment by cmdcolin** [comment]
yay no more eval :)

**Pull request merged**
