### PR TITLE
Add Nextstrain COVID storybook

### PR DESCRIPTION
**Pull request by elliothershberg**
This PR adds:

1. A test data file with some Nextstrain COVID data:

- an assembly config with the sequence
- tracks config with the gene map and entropy score (from Nextstrain diversity panel)
- a default session with these tracks loaded

2. A Storybook story to to the React linear genome view using the new data.

This should provide another good example of the embedded view, and might make further development on #1616 easier. Also could be useful for working on #1635 @teresam856

### CODE REVIEW

**Comment by cmdcolin** [comment]
This is fairly minor but in order to keep size of the repo down, storing the 0.6mb data file in s3 might be nice. 
There is a folder on s3://jbrowse.org/genomes/sars-cov2/

**Comment by cmdcolin** [comment]
kind of on the cusp of caring about file size as we obviously store pictures and stuff in our repo too...hard to say...those could be on s3 too technically

**Comment by elliothershberg** [comment]
@cmdcolin While it's a somewhat big file, I'd prefer in this instance to keep it with the rest of the test data. I feel like a really large amount of the time I'm figuring out how to add a new track my first visit is the test data. This test data contains some examples that aren't in other test data, and I think it is helpful to have the data and storybook both accessible.

**Comment by cmdcolin** [comment]
Note that not only will this file increase repo size but it will increase every subsequent download of our jbrowse bundle because the test_data folder is copied to every installation

**Comment by elliothershberg** [comment]
Hmm, what would be your thoughts on instead putting it in the storybook folder?

**Comment by cmdcolin** [comment]
Should be fine in storybook folder

**Pull request merged**
