### PR TITLE
React Linear View

### LINKED ISSUE #1027: embeddable-LGV state model and theme providers
In `packages/embeddable-linear-genome-view`:

Make some factory functions that make it easy to make a state tree root model, theme provider, and all the other tooling that a JB2 view needs in order to run. If you find yourself duplicating tons of code from elsewhere, try to refactor the core models to reduce duplication.

```jsx
let model = stateTreeFactory({
  assembly:{ /* full assembly config snapshot */ },
  tracks:[ /* array of full track snapshotIn */ ],
  plugins:[ /* optional list of runtime plugins to load */ ],
  location:"chr4:12345..234534",
  defaultSession:{
    /* session snapshot just for an LGV */
    bpPerPx: 1,
    displayedRegions: [ /* list of displayed regions */ ]
   },
  onChange:(mst_patch) => { console.log("something changed in here", mst_patch) }
})
let theme = useDefaultJBrowseTheme()

<ThemeProvider theme={theme}>
  <JBrowseLinearGenomeView  model={model}/>
</Theme>
```

This should not spawn any web workers, it will use the main-thread RPC driver. Should not require any webpack worker support.

Main tasks

- create a pluginManager with a set of core plugins that are necessary to make a linear genome view
- create a stateTreeFactory that is "easy to use"
- pass state tree model to the React component
- fix some small display issues when displaying the LGV in this standalone way

### PR DESCRIPTION
**Pull request by garrettjstevens**
This adds a linear genome view React component that functions as described in #1027. There are working examples in packages/jbrowse-linear-view/stories/JBrowseLinearView.stories.tsx.

Getting it to build in such a way as to be able to publish it to NPM is a bit tricky, since normally it would rely on the core plugins it uses being published to NPM, too. I'm working on a solution now (part of the reason this is still a draft).

If anyone wants to poke at some of the visual oddities (like the overview bar), feel free.

Resolves #1027

### CODE REVIEW

**Comment by garrettjstevens** [comment]
@scottcain if you want to try out some embedded linear view, first clone jbrowse-components and check out this branch (1027_embedded_lgv), then do:

```sh-session
$ yarn
$ cd packages/jbrowse-linear-view/
$ yarn storybook
```

The code for those three demos is in packages/jbrowse-linear-view/stories/JBrowseLinearView.stories.tsx

**Comment by cmdcolin** [comment]
Wow really nice work. The change drawer widget-> widget looks good to me, as well as the conceptual thing where it is popped up in a modal. I think it looks great.

The popup tracklist is pretty cool. The close button on the popup tracklist doesn't work but clicking away from it does
It think perhaps refname renaming does not work (see volvox 1000g track). If that is outside scope that is ok

I can try to continue to review but this is awesome

**Comment by cmdcolin** [comment]
NVM the "close button" i was clicking was the Filter "X" in the tracklist. We might want to add a modal header with an X perhaps just to help clarify

**Comment by rbuels** [comment]
jbrowse-core is being published to npm now as part of the plugin development work: https://www.npmjs.com/package/@gmod/jbrowse-core

**Comment by rbuels** [comment]
GDC plugin is out of the monorepo now, so just deleting that should fix some of these conflicts

**Comment by cmdcolin** [comment]
I pushed a merge master here 1027_embedded_lv_merge_master


The story book fails with some RPC errors with this merge however

Screenshot from 2020-07-15 13-58-15

**Pull request closed without merging**
