### PR TITLE
Sequence track translation frames

### LINKED ISSUE #134: add translation to SequenceRenderer
Support just 6-frame for genetic sequence.

There is now ProteinReferenceSequenceRenderer for protein reference sequences.

this is a refinement of #87

### LINKED ISSUE #209: Whitespace on sequence track
If you use MODEL.views[0].setNewView(0.871504157218443,21631.56634865568) on volvox sample data you'll see there is a little whitespace on the sequence track

Just wanted to make sure this didn't get lost, will probably get involved in a sequence track re-design that includes translation frames

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a proposal for adding translation frames to the reference sequence track

Fixes #134
Fixes #209 

localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-tsDuit99H (1)
localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-tsDuit99H

Renders it directly in SVG rather than canvas or div

### CODE REVIEW

**Comment by cmdcolin** [comment]
Note that this would also fix #209

**Comment by rbuels** [comment]
Pretty heavy on the DOM node count, wouldn't a canvas implementation be a lot faster?

**Comment by cmdcolin** [comment]
(a) not much more than what we currently have
(b) not much more or less than what you might see in a SVG features track
(c) goes toward svg export aim

**Comment by cmdcolin** [comment]
This PR started out as a canvas implementation but I actually preferred the declarative nature of rendering in jsx also

**Comment by cmdcolin** [comment]
Added contrastingTextColor

localhost_3000__config=test_data%2Fvolvox%2Fconfig json session=local-ZjjZyk6_x

**Comment by cmdcolin** [comment]
Now works with horizontally flipped and has showForward, showReverse and showTranslation track menu items

**Pull request merged**
