### PR TITLE
Add additionalContextMenuItemCallbacks to tracks

### PR DESCRIPTION
**Pull request by garrettjstevens**
This adds additionalContextMenuItemCallbacks to the blockBasedTrackModel. Plugins can add callbacks which return an array of zero or more menu items. These callbacks are evaluated for each right click, so the context menu items can react to whether or not the right click was on a feature, what type of feature was clicked on, etc. As an example:

```js
export default class SomePlugin extends Plugin {
  name = 'SomePlugin'

  install(pluginManager) {
    // install some stuff
  }

  configure(pluginManager) {
    const session = pluginManager.rootModel?.session
    const tracksAlreadyAddedTo = []
    autorun(() => {
      let views = []
      if (session.views) {
        views = session.views
      } else if (session.view) {
        views = [session.view]
      }

      views.forEach(view => {
        if (view.type === 'LinearGenomeView') {
          const { tracks } = view
          tracks.forEach(track => {
            if (
              track.type === 'VariantTrack' &&
              !tracksAlreadyAddedTo.includes(track.id)
            ) {
              tracksAlreadyAddedTo.push(track.id)
              track.addAdditionalContextMenuItemCallback(
                (feature, track, pluginManager) => {
                  const { session } = pluginManager.rootModel
                  const menuItem = {
                    label: 'Some menu item',
                    icon: SomeIcon,
                    onClick: session => {
                      // do some stuff
                    },
                  }
                  return [menuItem]
                },
              )
            }
          })
        }
      })
    })
  }
}
```

### CODE REVIEW

**Comment by garrettjstevens** [comment]
Discussion of a plugin implementing this here: https://github.com/GMOD/jbrowse-components/commit/5d8b97306938b5ba54f0479b818ab59c473f5f22#r41669085

**Comment by garrettjstevens** [comment]
I think the autorun code needs a bit of a different approach. Keeping 'tracksAlreadyAddedTo' is probably not the right thing to do. The autorun should probably go through all the views and tracks, and needs to **inspect the contents of the track's additional context menu items** in order to decide whether it needs to add its item, rather than keeping a list of what tracks it's added itself to.

_Originally posted by @rbuels in https://github.com/GMOD/jbrowse-components/pull/1129#issuecomment-679287029_

**Comment by garrettjstevens** [comment]
That seems interesting but the context menu is dynamically created on each feature click, and the code here is adding a custom callback called `addAdditionalContextMenuItemCallback` which returns an array of menu items given a feature for example?

_Originally posted by @cmdcolin in https://github.com/GMOD/jbrowse-components/pull/1129#issuecomment-679289336_

**Comment by garrettjstevens** [comment]
After talking with @rbuels, it looks like this may be a better way of adding the callback (works with the existing code):

```js
export default class SomePlugin extends Plugin {
  name = 'SomePlugin'

  install(pluginManager) {
    // install some stuff
  }

  configure(pluginManager) {
    const menuItemCallback = (feature, track) => {
      const menuItem = {
        label: 'Some menu item',
        icon: SomeIcon,
        onClick: session => {
          // do some stuff
        },
      }
      return [menuItem]
    }

    const session = pluginManager.rootModel?.session
    autorun(() => {
      const views = session?.views

      views.forEach(view => {
        if (view.type === 'LinearGenomeView') {
          const { tracks } = view
          tracks.forEach(track => {
            if (
              track.type === 'VariantTrack' &&
              !track.additionalContextMenuItemCallbacks.includes(
                menuItemCallback,
              )
            ) {
              track.addAdditionalContextMenuItemCallback(menuItemCallback)
            }
          })
        }
      })
    })
  }
}
```

**Comment by cmdcolin** [comment]
Nice :) I adapted that for my dotplot right click example

**Comment by cmdcolin** [comment]
Any updates on this one? Ready to merge?

**Pull request merged**
