### PR TITLE
Add position fixed for the resize handle.

### PR DESCRIPTION
**Pull request by cmdcolin**
This adds position: fixed and removes the left: from the resize handle. This appears to give good behavior for a fullscreen app.

### CODE REVIEW

**Comment by cmdcolin** [comment]
Caveat: jbrowse 1 had position: fixed but eventually removed it for better compatibility with embedded mode, since fixed doesn't play nicely with that.

With this in mind, if we think the drawer widget should remain inside JBrowse component div, then this PR should be skipped and a better solution should be created

**Comment by rbuels** [comment]
It’s kind of a question that gets to the vision for each product. Do we
want to support running JBrowse-web embedded? Or will JBrowse-lite,
JBrowse-image etc cover that scenario?

I kind of think we might explicitly rule out embedding for JBrowse-web,
what do you guys think?

**Comment by cmdcolin** [comment]
It seems like this PR is reasonable given the state of things with the drawer. Maybe we can merge for now and think about other options if needed.

**Comment by garrettjstevens** [comment]
I agree with Rob, I think this will be fine since we'll make a different version of JBrowse for embedding.

**Pull request merged**
