### PR TITLE
Add RegionsAdapter/SequenceAdapter, reorganize base adapters

### PR DESCRIPTION
**Pull request by garrettjstevens**
I was making a new sequence adapter, and realized that even if it only provided a list of regions and no sequence (like the `ChromSizesAdapter` does), there still had to be a `getFeatures()` that does nothing. This change makes it so that there is now a `BaseAdapter` class, which is extended by the `BaseFeatureDataAdapter` class (has `getFeatures()`), the `BaseRefNameAliasAdapter` interface (has `getRefNameAliases()`), and the `RegionsAdapter` interface (has `getRegions()`). There is a new interface `SequenceAdapter` that extends both BaseFeatureDataAdapter and RegionsAdapter (has both `getFeatures()` and `getRegions()`).

This allows checks like `isFeatureAdapter()` that will return `false` for `RegionsAdapter`s. A nice follow-up might be to store on the assembly in the assemblyManager whether the sequence has a `RegionsAdapter` or a `SequenceAdapter`, so that UI elements could react to that. For example, we could disable the reference sequence track in the track selector or disable the "get sequence" from the rubber band menu if a `ChromSizesAdapter` is being used.

This also adds a `FromConfigRegionsAdapter` for convenience, and removes `getRegions()` from the `FromConfigAdapter`, so if you want to use a sequence adapter from config you have to use the `FromConfigSequenceAdapter` or `FromConfigRegionsAdapter` (this helps avoid situations like [this](https://github.com/GMOD/jbrowse-components/issues/1623#issue-788495768), where `FromConfigAdapter` is used instead of `FromConfigSequenceAdapter`).

### CODE REVIEW

**Comment by cmdcolin** [comment]
This is fairly niche (seeming to affect ChromSizesAdapter and FromConfigAdapter only, currently), but it does solve some practical problems with those. Am I right in that assessment?

**Comment by cmdcolin** [comment]
I'm probably ok with this but it is sometimes hard to keep track of all our "base" concepts. Might be interesting if we had a little chart...

**Comment by garrettjstevens** [comment]
> This is fairly niche (seeming to affect ChromSizesAdapter and FromConfigAdapter only, currently), but it does solve some practical problems with those. Am I right in that assessment?

Yes, I think that's a fair assessment.

> I'm probably ok with this but it is sometimes hard to keep track of all our "base" concepts. Might be interesting if we had a little chart...

If the consensus is that this is an acceptable solution, I'll update the docs.

**Comment by cmdcolin** [comment]
There is an alternative approach where we perform this concept using the "capabilities" attribute, but capabilities isn't always a great fit...might just be better to embed it into the hierarchy.

There is maybe even the option to possibly remove the whole capabilities thing also..."check if object implements interface at runtime with typescript" https://stackoverflow.com/questions/33800497/check-if-an-object-implements-an-interface-at-runtime-with-typescript

**Comment by cmdcolin** [comment]
Just some food for thought, capabilities does work right now for certain things but it is a source of weirdness perhaps

**Comment by garrettjstevens** [comment]
This PR adds a few more user-defined type guards (like in that stackoverflow post) to the ones that were already in the BaseAdapter file, and I think we could use them to get rid of "capabilities". I think the only thing extra "capabilities" gives us is the ability to tell what methods a class has before it's instantiated. I don't think we use that feature, though, so maybe we're fine without it.

**Comment by cmdcolin** [comment]
> I think the only thing extra "capabilities" gives us is the ability to tell what methods a class has before it's instantiated.

It is used here
https://github.com/GMOD/jbrowse-components/blob/master/plugins/wiggle/src/LinearWiggleDisplay/models/model.ts#L253

**Comment by rbuels** [comment]
looks good, merge as discussed just now after updating the docs

**Pull request merged**
