### PR TITLE
Perform assembly loading on the main thread

### PR DESCRIPTION
**Pull request by cmdcolin**
This is an alternative to #1406 that performs assembly loading on the main thread

This improves loading time, and makes it so the assembly is waited on before the app is called initialized

### CODE REVIEW

**Comment by cmdcolin** [comment]
Note that the goals of this PR are knock-on effects from wanting to add a test for the location-search box, which means the assembly has to be initialized

Therefore we

- make LGV displaying conditional on the assembly being loaded (see the LGV initialized getter)
- and perform assembly loading in the main thread

If assembly loading is not done in the main thread, the loading time for a basic LGV is much worse because it has to wait on the webworker JS to download, parse, run, etc before anything is displayed

**Comment by cmdcolin** [comment]
The tests on this branch for me pass locally but do not pass on travis https://travis-ci.com/github/GMOD/jbrowse-components/builds/200457135

**Comment by cmdcolin** [comment]
Just a random other weird thing


yarn test --runInBand often fails with this error for me

node 14.15.0


```

Summary of all failing tests
 FAIL  plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.test.js
  ● <LinearGenomeView /> › renders one track, one region

    expect(received).toMatchSnapshot()

    Snapshot name: `<LinearGenomeView /> renders one track, one region 1`

    - Snapshot
    + Received

    @@ -163,30 +163,51 @@
                  <div
                    class="MuiFormControl-root MuiTextField-root makeStyles-headerRefName MuiFormControl-fullWidth"
                    style="margin: 7px;"
                  >
                    <div
    -                 class="MuiInputBase-root MuiOutlinedInput-root MuiAutocomplete-inputRoot MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-adornedEnd MuiOutlinedInput-adornedEnd"
    +                 class="MuiInputBase-root MuiOutlinedInput-root MuiAutocomplete-inputRoot MuiInputBase-disabled MuiOutlinedInput-disabled MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-adornedEnd MuiOutlinedInput-adornedEnd"
                      style="padding: 0px; height: 32px; background: rgba(255, 255, 255, 0.8);"
                    >
                      <input
                        aria-autocomplete="list"
                        aria-invalid="false"
                        autocapitalize="none"
                        autocomplete="off"
    -                   class="MuiInputBase-input MuiOutlinedInput-input MuiAutocomplete-input MuiAutocomplete-inputFocused MuiInputBase-inputAdornedEnd MuiOutlinedInput-inputAdornedEnd"
    +                   class="MuiInputBase-input MuiOutlinedInput-input MuiAutocomplete-input MuiAutocomplete-inputFocused MuiInputBase-disabled MuiOutlinedInput-disabled MuiInputBase-inputAdornedEnd MuiOutlinedInput-inputAdornedEnd"
    +                   disabled=""
                        id="refNameAutocomplete-lgv"
                        spellcheck="false"
                        type="text"
    -                   value="ctgA"
    +                   value=""
                      />
    +                 <div
    +                   class="MuiCircularProgress-root MuiCircularProgress-indeterminate"
    +                   role="progressbar"
    +                   style="width: 20px; height: 20px;"
    +                 >
    +                   <svg
    +                     class="MuiCircularProgress-svg"
    +                     viewBox="22 22 44 44"
    +                   >
    +                     <circle
    +                       class="MuiCircularProgress-circle MuiCircularProgress-circleIndeterminate"
    +                       cx="44"
    +                       cy="44"
    +                       fill="none"
    +                       r="20.2"
    +                       stroke-width="3.6"
    +                     />
    +                   </svg>
    +                 </div>
                      <div
                        class="MuiAutocomplete-endAdornment"
                      >
                        <button
                          aria-label="Open"
    -                     class="MuiButtonBase-root MuiIconButton-root MuiAutocomplete-popupIndicator"
    +                     class="MuiButtonBase-root MuiIconButton-root MuiAutocomplete-popupIndicator MuiIconButton-disabled MuiButtonBase-disabled"
    +                     disabled=""
                          tabindex="-1"
                          title="Open"
                          type="button"
                        >
                          <span
    @@ -201,13 +222,10 @@
                              <path
                                d="M7 10l5 5 5-5z"
                              />
                            </svg>
                          </span>
    -                     <span
    -                       class="MuiTouchRipple-root"
    -                     />
                        </button>
                      </div>
                      <fieldset
                        aria-hidden="true"
                        class="PrivateNotchedOutline-root MuiOutlinedInput-notchedOutline"
    @@ -246,11 +264,11 @@
                      </svg>
                      <input
                        aria-invalid="false"
                        class="MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart MuiOutlinedInput-inputAdornedStart"
                        type="text"
    -                   value="ctgA:1..100"
    +                   value=""
                      />
                      <fieldset
                        aria-hidden="true"
                        class="PrivateNotchedOutline-root MuiOutlinedInput-notchedOutline"
                        style="padding-left: 8px;"
    @@ -269,11 +287,11 @@
                </form>
              </div>
              <p
                class="MuiTypography-root makeStyles-bp MuiTypography-body2 MuiTypography-colorTextSecondary"
              >
    -           100 bp
    +           0 bp
              </p>
              <div
                class="makeStyles-container"
              >
                <button

      78 |     const { container, findByText } = render(<LinearGenomeView model={model} />)
      79 |     await findByText('Foo Track')
    > 80 |     expect(container.firstChild).toMatchSnapshot()
         |                                  ^
      81 |   })
      82 |   it('renders two tracks, two regions', async () => {
      83 |     const session = createTestSession()

      at _callee2$ (plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.test.js:80:34)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)


Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `yarn test -u` to update them.

Test Suites: 1 failed, 2 skipped, 120 passed, 121 of 123 total
Tests:       1 failed, 3 skipped, 458 passed, 462 total
Snapshots:   1 failed, 233 passed, 234 total
Time:        127.901s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by cmdcolin** [comment]
Could make this into another issue but would be interesting if someone can confirm

**Comment by cmdcolin** [comment]
This is now tests passing

**Comment by rbuels** [comment]
if CoreGetRegions and CoreGetRefNameAliases are no longer used, let's add deleting them to this PR

**Comment by cmdcolin** [comment]
I was somewhat comfortable with this

However, running git checkout origin/master test_data....This reverts the test_data/volvox/config.json back to volvox.2bit and then the tests fail...the volvox.2bit fails while the indexedfasta succeeds. This is somewhat concerning and may be worth looking into

**Comment by cmdcolin** [comment]
Traced the aforementioned loading failure of volvox.2bit to usage of jest.useFakeTimers being enabled (and then deep in http-range-fetcher depending on usage of a setTimeout). I disabled usage of useFakeTimers for now to fix

**Pull request merged**
