### PR TITLE
570 add circular view toggle fit window

### PR DESCRIPTION
**Pull request by peterkxie**
Add a fit to window lock feature in circular view

On lock mode: User can only zoom in up til model takes up full window size. Zoom in is disabled further until user either zooms out, increases window size, or unlocks

On unlock mode: User can freely zoom in

Additionally added a disable for the zoom out when model hits max base pairs per pixel. 
Minor detail that needs review before completion: what course of action is needed in the edge case that user resizes the window so small that even the smallest model cannot fit fully

### CODE REVIEW

**Comment by cmdcolin** [comment]
Congrats on your first PR :tada:

**Comment by cmdcolin** [comment]
My only initial comment would be to possibly add a test that ensures the behavior or some aspect of the behavior

**Comment by cmdcolin** [comment]
We don't always include a test in all our PR but it can be a good thing to aim for

**Comment by cmdcolin** [comment]
I am working on #693  and looked at how it behaves with this PR included. I am thinking that lock to window should not allow zoom out, it's just literally locked to the window. It's a matter of taste, but if I resize to a small window, and the make the window bigger, the circos stays small. This sort of just "feels weird" as a user seeing it locked in a way that makes it smaller but not in a way that makes it bigger

**Comment by peterkxie** [comment]
agree with the not allowing zoom out and resizing issue. Have a new implementation where zoom out is disabled when locked and the hover text instructs user to unlock to enable zoom out. As for resizing, now have it so anytime the height or width is resized, the circle is set to the biggest size (minBpPerPx). One thing I am considering is that when the circular view is generated by user adding one, have the model automatically be set to biggest size (minBpPerPx) and they must unlock to adjust the size in any way. Thoughts on this?

**Comment by cmdcolin** [comment]
>One thing I am considering is that when the circular view is generated by user adding one, have the model automatically be set to biggest size (minBpPerPx) and they must unlock to adjust the size in any way. Thoughts on this?

I would just say set to biggest size but not have it locked though

**Comment by peterkxie** [comment]
Original ticket #570 has it default to on when created, just wondering whether to stick with that or go in this new direction

**Comment by cmdcolin** [comment]
Hmm. I guess we just do that then. It's sort of a toss up...with sv inspector having the tiny circos and resizing the window it seems ok to have on.

**Comment by peterkxie** [comment]
to clarify, when adding a new circular view, I set it to locked mode and make model the largest size (minBpPerPx)? Current implementation before any changes is set to locked model and model is the smallest size (maxBpPerPx)

**Comment by cmdcolin** [comment]
Sounds right to me

**Pull request merged**
