### PR TITLE
GCContent adapter

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a sketch for a GCContent adapter 

Ref #281

Imports some utility functions from @jbrowse/plugin-wiggle, uses the sequenceAdapter/subadapter concept similar to CramAdapter, and there is a track is in config_demo.json for hg19

localhost_3000__config=test_data%2Fconfig_demo json session=local-947DkYCtt (2)

### CODE REVIEW

**Comment by cmdcolin** [comment]
Looks like there is a build error related to the direct import of statsUtils...could consider more properly exporting the statsUtils another way but that is a weird error

**Comment by garrettjstevens** [comment]
Now that our plugins can be built independently, we can't import from `src` of other plugins. Anything you want to use from the other plugin has to be exported at the top level of that plugin.

**Comment by cmdcolin** [comment]
This should be ready basically. We could potentially automatically generate a gccontent track for the assembly to make this more accessible to users, but the adapter type works pretty fine here

**Comment by cmdcolin** [comment]
There is some note in #1630 that the region stats code may get added to base adapter so all the adapters that use stats don't have to implement it in a custom way

**Pull request merged**
