### PR TITLE
Create MacOS universal build of jbrowse-desktop to help M1 macs

### PR DESCRIPTION
**Pull request by cmdcolin**
fixes https://github.com/GMOD/jbrowse-components/issues/4011

draft since untested

### CODE REVIEW

**Comment by cmdcolin** [comment]
log from @carolinebridge-oicr from this branch showing it might not work

```
  • electron-builder  version=24.6.4 os=22.6.0
  • loaded configuration  file=package.json ("build" field)
  • packaging       platform=darwin arch=x64 electron=27.0.1 appOutDir=dist/mac-universal-x64-temp
  • packaging       platform=darwin arch=arm64 electron=27.0.1 appOutDir=dist/mac-universal-arm64-temp
  • packaging       platform=darwin arch=universal electron=27.0.1 appOutDir=dist/mac-universal
  ⨯ Cannot read properties of undefined (reading 'link')  failedTask=build stackTrace=TypeError: Cannot read properties of undefined (reading 'link')
    at Filesystem.getFile (/Users/cbridge/Workspace/jbrowse-components/node_modules/@electron/asar/lib/filesystem.js:146:14)
    at Filesystem.getFile (/Users/cbridge/Workspace/jbrowse-components/node_modules/@electron/asar/lib/filesystem.js:147:19)
    at Object.module.exports.statFile (/Users/cbridge/Workspace/jbrowse-components/node_modules/@electron/asar/lib/asar.js:157:21)
    at buildUnpacked (/Users/cbridge/Workspace/jbrowse-components/node_modules/@electron/universal/src/asar-utils.ts:101:25)
    at Object.exports.mergeASARs (/Users/cbridge/Workspace/jbrowse-components/node_modules/@electron/universal/src/asar-utils.ts:114:3)
    at exports.makeUniversalApp (/Users/cbridge/Workspace/jbrowse-components/node_modules/@electron/universal/src/index.ts:235:13)
    at MacPackager.doPack (/Users/cbridge/Workspace/jbrowse-components/node_modules/app-builder-lib/src/macPackager.ts:129:9)
    at MacPackager.pack (/Users/cbridge/Workspace/jbrowse-components/node_modules/app-builder-lib/src/macPackager.ts:196:7)
    at Packager.doBuild (/Users/cbridge/Workspace/jbrowse-components/node_modules/app-builder-lib/src/packager.ts:442:9)
    at executeFinally (/Users/cbridge/Workspace/jbrowse-components/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/cbridge/Workspace/jbrowse-components/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/cbridge/Workspace/jbrowse-components/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/Users/cbridge/Workspace/jbrowse-components/node_modules/builder-util/src/promise.ts:12:14)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cmdcolin** [comment]
was updated with mergeASARs:false option which allowed build to work...awaiting confirmation from m1 users

**Comment by scottcain** [comment]
The app built for M1 appears to work fine for me. Is there anything else you want me to try?

**Comment by scottcain** [comment]
That is, I didn't try running the build myself--do you want that?

**Comment by cmdcolin** [comment]
@scottcain are you familiar with the rosetta concept that https://github.com/GMOD/jbrowse-components/discussions/4008 refers to? basically wondering whether the new build can be "used without rosetta"

**Comment by scottcain** [comment]
Only sort of familar with it: I'm pretty sure I installed when I got my M1 because I needed it for something (probably a python dependency :-/ I don't think it has a UI in system settings, but I'll do some research to see if it can be deactivated.

**Comment by scottcain** [comment]
Oh this is somewhat terrible: to remove rosetta, I have to boot into recovery mode and delete some system files:
https://developer.apple.com/forums/thread/669486
I'm not going to do that right now as I'm away from home and running on battery. I can try it tonight if you want.

**Comment by cmdcolin** [comment]
@scottcain if you want to can try out, @billzt appeared to confirm it worked in the other thread though!

**Pull request merged**
